/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as MarketingSupportRouteImport } from './routes/_marketing/support'
import { Route as MarketingSecurityRouteImport } from './routes/_marketing/security'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing/features'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile.index'
import { Route as AuthedOrgsIndexRouteImport } from './routes/_authed/orgs.index'
import { Route as MarketingCompareTestrailRouteImport } from './routes/_marketing/compare.testrail'
import { Route as MarketingCompareReportportalRouteImport } from './routes/_marketing/compare.reportportal'
import { Route as MarketingCompareDatadogRouteImport } from './routes/_marketing/compare.datadog'
import { Route as MarketingCompareAllureRouteImport } from './routes/_marketing/compare.allure'
import { Route as AuthedRRunIdRouteImport } from './routes/_authed/r.$runId'
import { Route as AuthedProfileSecurityRouteImport } from './routes/_authed/profile.security'
import { Route as AuthedProfileDangerRouteImport } from './routes/_authed/profile.danger'
import { Route as AuthedOrgsOrgIdRouteImport } from './routes/_authed/orgs.$orgId'
import { Route as AuthedOrgsOrgIdIndexRouteImport } from './routes/_authed/orgs.$orgId.index'
import { Route as AuthedOrgsOrgIdSettingsRouteImport } from './routes/_authed/orgs.$orgId.settings'
import { Route as AuthedOrgsOrgIdKeysRouteImport } from './routes/_authed/orgs.$orgId.keys'
import { Route as AuthedOrgsOrgIdBillingRouteImport } from './routes/_authed/orgs.$orgId.billing'
import { Route as AuthedOrgsOrgIdSettingsIndexRouteImport } from './routes/_authed/orgs.$orgId.settings.index'
import { Route as AuthedOrgsOrgIdProjectsIndexRouteImport } from './routes/_authed/orgs.$orgId.projects.index'
import { Route as AuthedOrgsOrgIdKeysIndexRouteImport } from './routes/_authed/orgs.$orgId.keys.index'
import { Route as AuthedOrgsOrgIdIntegrationsIndexRouteImport } from './routes/_authed/orgs.$orgId.integrations.index'
import { Route as AuthedOrgsOrgIdSettingsUsersRouteImport } from './routes/_authed/orgs.$orgId.settings.users'
import { Route as AuthedOrgsOrgIdSettingsSsoRouteImport } from './routes/_authed/orgs.$orgId.settings.sso'
import { Route as AuthedOrgsOrgIdSettingsDomainsRouteImport } from './routes/_authed/orgs.$orgId.settings.domains'
import { Route as AuthedOrgsOrgIdProjectsProjectIdRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId'
import { Route as AuthedOrgsOrgIdKeysMcpRouteImport } from './routes/_authed/orgs.$orgId.keys.mcp'
import { Route as AuthedOrgsOrgIdKeysIngestionRouteImport } from './routes/_authed/orgs.$orgId.keys.ingestion'
import { Route as AuthedOrgsOrgIdIntegrationsSlackRouteImport } from './routes/_authed/orgs.$orgId.integrations.slack'
import { Route as AuthedOrgsOrgIdIntegrationsGithubRouteImport } from './routes/_authed/orgs.$orgId.integrations.github'
import { Route as AuthedOrgsOrgIdProjectsProjectIdIndexRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.index'
import { Route as AuthedOrgsOrgIdProjectsProjectIdSettingsRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.settings'
import { Route as AuthedOrgsOrgIdProjectsProjectIdFlakyRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.flaky'
import { Route as AuthedOrgsOrgIdProjectsProjectIdFailingRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.failing'
import { Route as AuthedOrgsOrgIdProjectsProjectIdExplorerRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.explorer'
import { Route as AuthedOrgsOrgIdProjectsProjectIdRunsIndexRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.runs.index'
import { Route as AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.explorer_.$testId'
import { Route as AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.runs.$runId.index'
import { Route as AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.runs.$runId.file'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingSupportRoute = MarketingSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingSecurityRoute = MarketingSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProfileRoute,
} as any)
const AuthedOrgsIndexRoute = AuthedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const MarketingCompareTestrailRoute =
  MarketingCompareTestrailRouteImport.update({
    id: '/compare/testrail',
    path: '/compare/testrail',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingCompareReportportalRoute =
  MarketingCompareReportportalRouteImport.update({
    id: '/compare/reportportal',
    path: '/compare/reportportal',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingCompareDatadogRoute = MarketingCompareDatadogRouteImport.update({
  id: '/compare/datadog',
  path: '/compare/datadog',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingCompareAllureRoute = MarketingCompareAllureRouteImport.update({
  id: '/compare/allure',
  path: '/compare/allure',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const AuthedRRunIdRoute = AuthedRRunIdRouteImport.update({
  id: '/r/$runId',
  path: '/r/$runId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileSecurityRoute = AuthedProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedProfileRoute,
} as any)
const AuthedProfileDangerRoute = AuthedProfileDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => AuthedProfileRoute,
} as any)
const AuthedOrgsOrgIdRoute = AuthedOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrgsOrgIdIndexRoute = AuthedOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdSettingsRoute = AuthedOrgsOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdKeysRoute = AuthedOrgsOrgIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdBillingRoute = AuthedOrgsOrgIdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdSettingsIndexRoute =
  AuthedOrgsOrgIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgIdSettingsRoute,
  } as any)
const AuthedOrgsOrgIdProjectsIndexRoute =
  AuthedOrgsOrgIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdKeysIndexRoute =
  AuthedOrgsOrgIdKeysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgIdKeysRoute,
  } as any)
const AuthedOrgsOrgIdIntegrationsIndexRoute =
  AuthedOrgsOrgIdIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdSettingsUsersRoute =
  AuthedOrgsOrgIdSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthedOrgsOrgIdSettingsRoute,
  } as any)
const AuthedOrgsOrgIdSettingsSsoRoute =
  AuthedOrgsOrgIdSettingsSsoRouteImport.update({
    id: '/sso',
    path: '/sso',
    getParentRoute: () => AuthedOrgsOrgIdSettingsRoute,
  } as any)
const AuthedOrgsOrgIdSettingsDomainsRoute =
  AuthedOrgsOrgIdSettingsDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthedOrgsOrgIdSettingsRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdRoute =
  AuthedOrgsOrgIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdKeysMcpRoute = AuthedOrgsOrgIdKeysMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthedOrgsOrgIdKeysRoute,
} as any)
const AuthedOrgsOrgIdKeysIngestionRoute =
  AuthedOrgsOrgIdKeysIngestionRouteImport.update({
    id: '/ingestion',
    path: '/ingestion',
    getParentRoute: () => AuthedOrgsOrgIdKeysRoute,
  } as any)
const AuthedOrgsOrgIdIntegrationsSlackRoute =
  AuthedOrgsOrgIdIntegrationsSlackRouteImport.update({
    id: '/integrations/slack',
    path: '/integrations/slack',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdIntegrationsGithubRoute =
  AuthedOrgsOrgIdIntegrationsGithubRouteImport.update({
    id: '/integrations/github',
    path: '/integrations/github',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdIndexRoute =
  AuthedOrgsOrgIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdSettingsRoute =
  AuthedOrgsOrgIdProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdFlakyRoute =
  AuthedOrgsOrgIdProjectsProjectIdFlakyRouteImport.update({
    id: '/flaky',
    path: '/flaky',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdFailingRoute =
  AuthedOrgsOrgIdProjectsProjectIdFailingRouteImport.update({
    id: '/failing',
    path: '/failing',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdExplorerRoute =
  AuthedOrgsOrgIdProjectsProjectIdExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute =
  AuthedOrgsOrgIdProjectsProjectIdRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute =
  AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRouteImport.update({
    id: '/explorer_/$testId',
    path: '/explorer/$testId',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute =
  AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRouteImport.update({
    id: '/runs/$runId/',
    path: '/runs/$runId/',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute =
  AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRouteImport.update({
    id: '/runs/$runId/file',
    path: '/runs/$runId/file',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/profile': typeof AuthedProfileRouteWithChildren
  '/features': typeof MarketingFeaturesRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/security': typeof MarketingSecurityRoute
  '/support': typeof MarketingSupportRoute
  '/terms': typeof MarketingTermsRoute
  '/orgs/$orgId': typeof AuthedOrgsOrgIdRouteWithChildren
  '/profile/danger': typeof AuthedProfileDangerRoute
  '/profile/security': typeof AuthedProfileSecurityRoute
  '/r/$runId': typeof AuthedRRunIdRoute
  '/compare/allure': typeof MarketingCompareAllureRoute
  '/compare/datadog': typeof MarketingCompareDatadogRoute
  '/compare/reportportal': typeof MarketingCompareReportportalRoute
  '/compare/testrail': typeof MarketingCompareTestrailRoute
  '/orgs/': typeof AuthedOrgsIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/orgs/$orgId/billing': typeof AuthedOrgsOrgIdBillingRoute
  '/orgs/$orgId/keys': typeof AuthedOrgsOrgIdKeysRouteWithChildren
  '/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsRouteWithChildren
  '/orgs/$orgId/': typeof AuthedOrgsOrgIdIndexRoute
  '/orgs/$orgId/integrations/github': typeof AuthedOrgsOrgIdIntegrationsGithubRoute
  '/orgs/$orgId/integrations/slack': typeof AuthedOrgsOrgIdIntegrationsSlackRoute
  '/orgs/$orgId/keys/ingestion': typeof AuthedOrgsOrgIdKeysIngestionRoute
  '/orgs/$orgId/keys/mcp': typeof AuthedOrgsOrgIdKeysMcpRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren
  '/orgs/$orgId/settings/domains': typeof AuthedOrgsOrgIdSettingsDomainsRoute
  '/orgs/$orgId/settings/sso': typeof AuthedOrgsOrgIdSettingsSsoRoute
  '/orgs/$orgId/settings/users': typeof AuthedOrgsOrgIdSettingsUsersRoute
  '/orgs/$orgId/integrations/': typeof AuthedOrgsOrgIdIntegrationsIndexRoute
  '/orgs/$orgId/keys/': typeof AuthedOrgsOrgIdKeysIndexRoute
  '/orgs/$orgId/projects/': typeof AuthedOrgsOrgIdProjectsIndexRoute
  '/orgs/$orgId/settings/': typeof AuthedOrgsOrgIdSettingsIndexRoute
  '/orgs/$orgId/projects/$projectId/explorer': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRoute
  '/orgs/$orgId/projects/$projectId/failing': typeof AuthedOrgsOrgIdProjectsProjectIdFailingRoute
  '/orgs/$orgId/projects/$projectId/flaky': typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRoute
  '/orgs/$orgId/projects/$projectId/settings': typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/orgs/$orgId/projects/$projectId/': typeof AuthedOrgsOrgIdProjectsProjectIdIndexRoute
  '/orgs/$orgId/projects/$projectId/explorer/$testId': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute
  '/orgs/$orgId/projects/$projectId/runs/': typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute
  '/orgs/$orgId/projects/$projectId/runs/$runId/file': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute
  '/orgs/$orgId/projects/$projectId/runs/$runId/': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/features': typeof MarketingFeaturesRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/security': typeof MarketingSecurityRoute
  '/support': typeof MarketingSupportRoute
  '/terms': typeof MarketingTermsRoute
  '/profile/danger': typeof AuthedProfileDangerRoute
  '/profile/security': typeof AuthedProfileSecurityRoute
  '/r/$runId': typeof AuthedRRunIdRoute
  '/compare/allure': typeof MarketingCompareAllureRoute
  '/compare/datadog': typeof MarketingCompareDatadogRoute
  '/compare/reportportal': typeof MarketingCompareReportportalRoute
  '/compare/testrail': typeof MarketingCompareTestrailRoute
  '/orgs': typeof AuthedOrgsIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/orgs/$orgId/billing': typeof AuthedOrgsOrgIdBillingRoute
  '/orgs/$orgId': typeof AuthedOrgsOrgIdIndexRoute
  '/orgs/$orgId/integrations/github': typeof AuthedOrgsOrgIdIntegrationsGithubRoute
  '/orgs/$orgId/integrations/slack': typeof AuthedOrgsOrgIdIntegrationsSlackRoute
  '/orgs/$orgId/keys/ingestion': typeof AuthedOrgsOrgIdKeysIngestionRoute
  '/orgs/$orgId/keys/mcp': typeof AuthedOrgsOrgIdKeysMcpRoute
  '/orgs/$orgId/settings/domains': typeof AuthedOrgsOrgIdSettingsDomainsRoute
  '/orgs/$orgId/settings/sso': typeof AuthedOrgsOrgIdSettingsSsoRoute
  '/orgs/$orgId/settings/users': typeof AuthedOrgsOrgIdSettingsUsersRoute
  '/orgs/$orgId/integrations': typeof AuthedOrgsOrgIdIntegrationsIndexRoute
  '/orgs/$orgId/keys': typeof AuthedOrgsOrgIdKeysIndexRoute
  '/orgs/$orgId/projects': typeof AuthedOrgsOrgIdProjectsIndexRoute
  '/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsIndexRoute
  '/orgs/$orgId/projects/$projectId/explorer': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRoute
  '/orgs/$orgId/projects/$projectId/failing': typeof AuthedOrgsOrgIdProjectsProjectIdFailingRoute
  '/orgs/$orgId/projects/$projectId/flaky': typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRoute
  '/orgs/$orgId/projects/$projectId/settings': typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthedOrgsOrgIdProjectsProjectIdIndexRoute
  '/orgs/$orgId/projects/$projectId/explorer/$testId': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute
  '/orgs/$orgId/projects/$projectId/runs': typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute
  '/orgs/$orgId/projects/$projectId/runs/$runId/file': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute
  '/orgs/$orgId/projects/$projectId/runs/$runId': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/_authed/profile': typeof AuthedProfileRouteWithChildren
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/security': typeof MarketingSecurityRoute
  '/_marketing/support': typeof MarketingSupportRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_authed/orgs/$orgId': typeof AuthedOrgsOrgIdRouteWithChildren
  '/_authed/profile/danger': typeof AuthedProfileDangerRoute
  '/_authed/profile/security': typeof AuthedProfileSecurityRoute
  '/_authed/r/$runId': typeof AuthedRRunIdRoute
  '/_marketing/compare/allure': typeof MarketingCompareAllureRoute
  '/_marketing/compare/datadog': typeof MarketingCompareDatadogRoute
  '/_marketing/compare/reportportal': typeof MarketingCompareReportportalRoute
  '/_marketing/compare/testrail': typeof MarketingCompareTestrailRoute
  '/_authed/orgs/': typeof AuthedOrgsIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/orgs/$orgId/billing': typeof AuthedOrgsOrgIdBillingRoute
  '/_authed/orgs/$orgId/keys': typeof AuthedOrgsOrgIdKeysRouteWithChildren
  '/_authed/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsRouteWithChildren
  '/_authed/orgs/$orgId/': typeof AuthedOrgsOrgIdIndexRoute
  '/_authed/orgs/$orgId/integrations/github': typeof AuthedOrgsOrgIdIntegrationsGithubRoute
  '/_authed/orgs/$orgId/integrations/slack': typeof AuthedOrgsOrgIdIntegrationsSlackRoute
  '/_authed/orgs/$orgId/keys/ingestion': typeof AuthedOrgsOrgIdKeysIngestionRoute
  '/_authed/orgs/$orgId/keys/mcp': typeof AuthedOrgsOrgIdKeysMcpRoute
  '/_authed/orgs/$orgId/projects/$projectId': typeof AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren
  '/_authed/orgs/$orgId/settings/domains': typeof AuthedOrgsOrgIdSettingsDomainsRoute
  '/_authed/orgs/$orgId/settings/sso': typeof AuthedOrgsOrgIdSettingsSsoRoute
  '/_authed/orgs/$orgId/settings/users': typeof AuthedOrgsOrgIdSettingsUsersRoute
  '/_authed/orgs/$orgId/integrations/': typeof AuthedOrgsOrgIdIntegrationsIndexRoute
  '/_authed/orgs/$orgId/keys/': typeof AuthedOrgsOrgIdKeysIndexRoute
  '/_authed/orgs/$orgId/projects/': typeof AuthedOrgsOrgIdProjectsIndexRoute
  '/_authed/orgs/$orgId/settings/': typeof AuthedOrgsOrgIdSettingsIndexRoute
  '/_authed/orgs/$orgId/projects/$projectId/explorer': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRoute
  '/_authed/orgs/$orgId/projects/$projectId/failing': typeof AuthedOrgsOrgIdProjectsProjectIdFailingRoute
  '/_authed/orgs/$orgId/projects/$projectId/flaky': typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRoute
  '/_authed/orgs/$orgId/projects/$projectId/settings': typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/_authed/orgs/$orgId/projects/$projectId/': typeof AuthedOrgsOrgIdProjectsProjectIdIndexRoute
  '/_authed/orgs/$orgId/projects/$projectId/explorer_/$testId': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute
  '/_authed/orgs/$orgId/projects/$projectId/runs/': typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute
  '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/file': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute
  '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/profile'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/support'
    | '/terms'
    | '/orgs/$orgId'
    | '/profile/danger'
    | '/profile/security'
    | '/r/$runId'
    | '/compare/allure'
    | '/compare/datadog'
    | '/compare/reportportal'
    | '/compare/testrail'
    | '/orgs/'
    | '/profile/'
    | '/orgs/$orgId/billing'
    | '/orgs/$orgId/keys'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/integrations/github'
    | '/orgs/$orgId/integrations/slack'
    | '/orgs/$orgId/keys/ingestion'
    | '/orgs/$orgId/keys/mcp'
    | '/orgs/$orgId/projects/$projectId'
    | '/orgs/$orgId/settings/domains'
    | '/orgs/$orgId/settings/sso'
    | '/orgs/$orgId/settings/users'
    | '/orgs/$orgId/integrations/'
    | '/orgs/$orgId/keys/'
    | '/orgs/$orgId/projects/'
    | '/orgs/$orgId/settings/'
    | '/orgs/$orgId/projects/$projectId/explorer'
    | '/orgs/$orgId/projects/$projectId/failing'
    | '/orgs/$orgId/projects/$projectId/flaky'
    | '/orgs/$orgId/projects/$projectId/settings'
    | '/orgs/$orgId/projects/$projectId/'
    | '/orgs/$orgId/projects/$projectId/explorer/$testId'
    | '/orgs/$orgId/projects/$projectId/runs/'
    | '/orgs/$orgId/projects/$projectId/runs/$runId/file'
    | '/orgs/$orgId/projects/$projectId/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/support'
    | '/terms'
    | '/profile/danger'
    | '/profile/security'
    | '/r/$runId'
    | '/compare/allure'
    | '/compare/datadog'
    | '/compare/reportportal'
    | '/compare/testrail'
    | '/orgs'
    | '/profile'
    | '/orgs/$orgId/billing'
    | '/orgs/$orgId'
    | '/orgs/$orgId/integrations/github'
    | '/orgs/$orgId/integrations/slack'
    | '/orgs/$orgId/keys/ingestion'
    | '/orgs/$orgId/keys/mcp'
    | '/orgs/$orgId/settings/domains'
    | '/orgs/$orgId/settings/sso'
    | '/orgs/$orgId/settings/users'
    | '/orgs/$orgId/integrations'
    | '/orgs/$orgId/keys'
    | '/orgs/$orgId/projects'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/projects/$projectId/explorer'
    | '/orgs/$orgId/projects/$projectId/failing'
    | '/orgs/$orgId/projects/$projectId/flaky'
    | '/orgs/$orgId/projects/$projectId/settings'
    | '/orgs/$orgId/projects/$projectId'
    | '/orgs/$orgId/projects/$projectId/explorer/$testId'
    | '/orgs/$orgId/projects/$projectId/runs'
    | '/orgs/$orgId/projects/$projectId/runs/$runId/file'
    | '/orgs/$orgId/projects/$projectId/runs/$runId'
  id:
    | '__root__'
    | '/_authed'
    | '/_marketing'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/_authed/profile'
    | '/_marketing/features'
    | '/_marketing/pricing'
    | '/_marketing/privacy'
    | '/_marketing/security'
    | '/_marketing/support'
    | '/_marketing/terms'
    | '/_marketing/'
    | '/_authed/orgs/$orgId'
    | '/_authed/profile/danger'
    | '/_authed/profile/security'
    | '/_authed/r/$runId'
    | '/_marketing/compare/allure'
    | '/_marketing/compare/datadog'
    | '/_marketing/compare/reportportal'
    | '/_marketing/compare/testrail'
    | '/_authed/orgs/'
    | '/_authed/profile/'
    | '/_authed/orgs/$orgId/billing'
    | '/_authed/orgs/$orgId/keys'
    | '/_authed/orgs/$orgId/settings'
    | '/_authed/orgs/$orgId/'
    | '/_authed/orgs/$orgId/integrations/github'
    | '/_authed/orgs/$orgId/integrations/slack'
    | '/_authed/orgs/$orgId/keys/ingestion'
    | '/_authed/orgs/$orgId/keys/mcp'
    | '/_authed/orgs/$orgId/projects/$projectId'
    | '/_authed/orgs/$orgId/settings/domains'
    | '/_authed/orgs/$orgId/settings/sso'
    | '/_authed/orgs/$orgId/settings/users'
    | '/_authed/orgs/$orgId/integrations/'
    | '/_authed/orgs/$orgId/keys/'
    | '/_authed/orgs/$orgId/projects/'
    | '/_authed/orgs/$orgId/settings/'
    | '/_authed/orgs/$orgId/projects/$projectId/explorer'
    | '/_authed/orgs/$orgId/projects/$projectId/failing'
    | '/_authed/orgs/$orgId/projects/$projectId/flaky'
    | '/_authed/orgs/$orgId/projects/$projectId/settings'
    | '/_authed/orgs/$orgId/projects/$projectId/'
    | '/_authed/orgs/$orgId/projects/$projectId/explorer_/$testId'
    | '/_authed/orgs/$orgId/projects/$projectId/runs/'
    | '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/file'
    | '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/support': {
      id: '/_marketing/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof MarketingSupportRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/security': {
      id: '/_marketing/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof MarketingSecurityRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedProfileRoute
    }
    '/_authed/orgs/': {
      id: '/_authed/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthedOrgsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_marketing/compare/testrail': {
      id: '/_marketing/compare/testrail'
      path: '/compare/testrail'
      fullPath: '/compare/testrail'
      preLoaderRoute: typeof MarketingCompareTestrailRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/compare/reportportal': {
      id: '/_marketing/compare/reportportal'
      path: '/compare/reportportal'
      fullPath: '/compare/reportportal'
      preLoaderRoute: typeof MarketingCompareReportportalRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/compare/datadog': {
      id: '/_marketing/compare/datadog'
      path: '/compare/datadog'
      fullPath: '/compare/datadog'
      preLoaderRoute: typeof MarketingCompareDatadogRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/compare/allure': {
      id: '/_marketing/compare/allure'
      path: '/compare/allure'
      fullPath: '/compare/allure'
      preLoaderRoute: typeof MarketingCompareAllureRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_authed/r/$runId': {
      id: '/_authed/r/$runId'
      path: '/r/$runId'
      fullPath: '/r/$runId'
      preLoaderRoute: typeof AuthedRRunIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/security': {
      id: '/_authed/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AuthedProfileSecurityRouteImport
      parentRoute: typeof AuthedProfileRoute
    }
    '/_authed/profile/danger': {
      id: '/_authed/profile/danger'
      path: '/danger'
      fullPath: '/profile/danger'
      preLoaderRoute: typeof AuthedProfileDangerRouteImport
      parentRoute: typeof AuthedProfileRoute
    }
    '/_authed/orgs/$orgId': {
      id: '/_authed/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthedOrgsOrgIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orgs/$orgId/': {
      id: '/_authed/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/settings': {
      id: '/_authed/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthedOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/keys': {
      id: '/_authed/orgs/$orgId/keys'
      path: '/keys'
      fullPath: '/orgs/$orgId/keys'
      preLoaderRoute: typeof AuthedOrgsOrgIdKeysRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/billing': {
      id: '/_authed/orgs/$orgId/billing'
      path: '/billing'
      fullPath: '/orgs/$orgId/billing'
      preLoaderRoute: typeof AuthedOrgsOrgIdBillingRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/settings/': {
      id: '/_authed/orgs/$orgId/settings/'
      path: '/'
      fullPath: '/orgs/$orgId/settings/'
      preLoaderRoute: typeof AuthedOrgsOrgIdSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdSettingsRoute
    }
    '/_authed/orgs/$orgId/projects/': {
      id: '/_authed/orgs/$orgId/projects/'
      path: '/projects'
      fullPath: '/orgs/$orgId/projects/'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/keys/': {
      id: '/_authed/orgs/$orgId/keys/'
      path: '/'
      fullPath: '/orgs/$orgId/keys/'
      preLoaderRoute: typeof AuthedOrgsOrgIdKeysIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdKeysRoute
    }
    '/_authed/orgs/$orgId/integrations/': {
      id: '/_authed/orgs/$orgId/integrations/'
      path: '/integrations'
      fullPath: '/orgs/$orgId/integrations/'
      preLoaderRoute: typeof AuthedOrgsOrgIdIntegrationsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/settings/users': {
      id: '/_authed/orgs/$orgId/settings/users'
      path: '/users'
      fullPath: '/orgs/$orgId/settings/users'
      preLoaderRoute: typeof AuthedOrgsOrgIdSettingsUsersRouteImport
      parentRoute: typeof AuthedOrgsOrgIdSettingsRoute
    }
    '/_authed/orgs/$orgId/settings/sso': {
      id: '/_authed/orgs/$orgId/settings/sso'
      path: '/sso'
      fullPath: '/orgs/$orgId/settings/sso'
      preLoaderRoute: typeof AuthedOrgsOrgIdSettingsSsoRouteImport
      parentRoute: typeof AuthedOrgsOrgIdSettingsRoute
    }
    '/_authed/orgs/$orgId/settings/domains': {
      id: '/_authed/orgs/$orgId/settings/domains'
      path: '/domains'
      fullPath: '/orgs/$orgId/settings/domains'
      preLoaderRoute: typeof AuthedOrgsOrgIdSettingsDomainsRouteImport
      parentRoute: typeof AuthedOrgsOrgIdSettingsRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId': {
      id: '/_authed/orgs/$orgId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/orgs/$orgId/projects/$projectId'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/keys/mcp': {
      id: '/_authed/orgs/$orgId/keys/mcp'
      path: '/mcp'
      fullPath: '/orgs/$orgId/keys/mcp'
      preLoaderRoute: typeof AuthedOrgsOrgIdKeysMcpRouteImport
      parentRoute: typeof AuthedOrgsOrgIdKeysRoute
    }
    '/_authed/orgs/$orgId/keys/ingestion': {
      id: '/_authed/orgs/$orgId/keys/ingestion'
      path: '/ingestion'
      fullPath: '/orgs/$orgId/keys/ingestion'
      preLoaderRoute: typeof AuthedOrgsOrgIdKeysIngestionRouteImport
      parentRoute: typeof AuthedOrgsOrgIdKeysRoute
    }
    '/_authed/orgs/$orgId/integrations/slack': {
      id: '/_authed/orgs/$orgId/integrations/slack'
      path: '/integrations/slack'
      fullPath: '/orgs/$orgId/integrations/slack'
      preLoaderRoute: typeof AuthedOrgsOrgIdIntegrationsSlackRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/integrations/github': {
      id: '/_authed/orgs/$orgId/integrations/github'
      path: '/integrations/github'
      fullPath: '/orgs/$orgId/integrations/github'
      preLoaderRoute: typeof AuthedOrgsOrgIdIntegrationsGithubRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/': {
      id: '/_authed/orgs/$orgId/projects/$projectId/'
      path: '/'
      fullPath: '/orgs/$orgId/projects/$projectId/'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/settings': {
      id: '/_authed/orgs/$orgId/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/flaky': {
      id: '/_authed/orgs/$orgId/projects/$projectId/flaky'
      path: '/flaky'
      fullPath: '/orgs/$orgId/projects/$projectId/flaky'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/failing': {
      id: '/_authed/orgs/$orgId/projects/$projectId/failing'
      path: '/failing'
      fullPath: '/orgs/$orgId/projects/$projectId/failing'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdFailingRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/explorer': {
      id: '/_authed/orgs/$orgId/projects/$projectId/explorer'
      path: '/explorer'
      fullPath: '/orgs/$orgId/projects/$projectId/explorer'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/runs/': {
      id: '/_authed/orgs/$orgId/projects/$projectId/runs/'
      path: '/runs'
      fullPath: '/orgs/$orgId/projects/$projectId/runs/'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/explorer_/$testId': {
      id: '/_authed/orgs/$orgId/projects/$projectId/explorer_/$testId'
      path: '/explorer/$testId'
      fullPath: '/orgs/$orgId/projects/$projectId/explorer/$testId'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/': {
      id: '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/'
      path: '/runs/$runId'
      fullPath: '/orgs/$orgId/projects/$projectId/runs/$runId/'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/file': {
      id: '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/file'
      path: '/runs/$runId/file'
      fullPath: '/orgs/$orgId/projects/$projectId/runs/$runId/file'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
  }
}

interface AuthedProfileRouteChildren {
  AuthedProfileDangerRoute: typeof AuthedProfileDangerRoute
  AuthedProfileSecurityRoute: typeof AuthedProfileSecurityRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedProfileRouteChildren: AuthedProfileRouteChildren = {
  AuthedProfileDangerRoute: AuthedProfileDangerRoute,
  AuthedProfileSecurityRoute: AuthedProfileSecurityRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedProfileRouteWithChildren = AuthedProfileRoute._addFileChildren(
  AuthedProfileRouteChildren,
)

interface AuthedOrgsOrgIdKeysRouteChildren {
  AuthedOrgsOrgIdKeysIngestionRoute: typeof AuthedOrgsOrgIdKeysIngestionRoute
  AuthedOrgsOrgIdKeysMcpRoute: typeof AuthedOrgsOrgIdKeysMcpRoute
  AuthedOrgsOrgIdKeysIndexRoute: typeof AuthedOrgsOrgIdKeysIndexRoute
}

const AuthedOrgsOrgIdKeysRouteChildren: AuthedOrgsOrgIdKeysRouteChildren = {
  AuthedOrgsOrgIdKeysIngestionRoute: AuthedOrgsOrgIdKeysIngestionRoute,
  AuthedOrgsOrgIdKeysMcpRoute: AuthedOrgsOrgIdKeysMcpRoute,
  AuthedOrgsOrgIdKeysIndexRoute: AuthedOrgsOrgIdKeysIndexRoute,
}

const AuthedOrgsOrgIdKeysRouteWithChildren =
  AuthedOrgsOrgIdKeysRoute._addFileChildren(AuthedOrgsOrgIdKeysRouteChildren)

interface AuthedOrgsOrgIdSettingsRouteChildren {
  AuthedOrgsOrgIdSettingsDomainsRoute: typeof AuthedOrgsOrgIdSettingsDomainsRoute
  AuthedOrgsOrgIdSettingsSsoRoute: typeof AuthedOrgsOrgIdSettingsSsoRoute
  AuthedOrgsOrgIdSettingsUsersRoute: typeof AuthedOrgsOrgIdSettingsUsersRoute
  AuthedOrgsOrgIdSettingsIndexRoute: typeof AuthedOrgsOrgIdSettingsIndexRoute
}

const AuthedOrgsOrgIdSettingsRouteChildren: AuthedOrgsOrgIdSettingsRouteChildren =
  {
    AuthedOrgsOrgIdSettingsDomainsRoute: AuthedOrgsOrgIdSettingsDomainsRoute,
    AuthedOrgsOrgIdSettingsSsoRoute: AuthedOrgsOrgIdSettingsSsoRoute,
    AuthedOrgsOrgIdSettingsUsersRoute: AuthedOrgsOrgIdSettingsUsersRoute,
    AuthedOrgsOrgIdSettingsIndexRoute: AuthedOrgsOrgIdSettingsIndexRoute,
  }

const AuthedOrgsOrgIdSettingsRouteWithChildren =
  AuthedOrgsOrgIdSettingsRoute._addFileChildren(
    AuthedOrgsOrgIdSettingsRouteChildren,
  )

interface AuthedOrgsOrgIdProjectsProjectIdRouteChildren {
  AuthedOrgsOrgIdProjectsProjectIdExplorerRoute: typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRoute
  AuthedOrgsOrgIdProjectsProjectIdFailingRoute: typeof AuthedOrgsOrgIdProjectsProjectIdFailingRoute
  AuthedOrgsOrgIdProjectsProjectIdFlakyRoute: typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRoute
  AuthedOrgsOrgIdProjectsProjectIdSettingsRoute: typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRoute
  AuthedOrgsOrgIdProjectsProjectIdIndexRoute: typeof AuthedOrgsOrgIdProjectsProjectIdIndexRoute
  AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute: typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute
  AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute
  AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute
  AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute
}

const AuthedOrgsOrgIdProjectsProjectIdRouteChildren: AuthedOrgsOrgIdProjectsProjectIdRouteChildren =
  {
    AuthedOrgsOrgIdProjectsProjectIdExplorerRoute:
      AuthedOrgsOrgIdProjectsProjectIdExplorerRoute,
    AuthedOrgsOrgIdProjectsProjectIdFailingRoute:
      AuthedOrgsOrgIdProjectsProjectIdFailingRoute,
    AuthedOrgsOrgIdProjectsProjectIdFlakyRoute:
      AuthedOrgsOrgIdProjectsProjectIdFlakyRoute,
    AuthedOrgsOrgIdProjectsProjectIdSettingsRoute:
      AuthedOrgsOrgIdProjectsProjectIdSettingsRoute,
    AuthedOrgsOrgIdProjectsProjectIdIndexRoute:
      AuthedOrgsOrgIdProjectsProjectIdIndexRoute,
    AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute:
      AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute,
    AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute:
      AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute,
    AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute:
      AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute,
    AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute:
      AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute,
  }

const AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren =
  AuthedOrgsOrgIdProjectsProjectIdRoute._addFileChildren(
    AuthedOrgsOrgIdProjectsProjectIdRouteChildren,
  )

interface AuthedOrgsOrgIdRouteChildren {
  AuthedOrgsOrgIdBillingRoute: typeof AuthedOrgsOrgIdBillingRoute
  AuthedOrgsOrgIdKeysRoute: typeof AuthedOrgsOrgIdKeysRouteWithChildren
  AuthedOrgsOrgIdSettingsRoute: typeof AuthedOrgsOrgIdSettingsRouteWithChildren
  AuthedOrgsOrgIdIndexRoute: typeof AuthedOrgsOrgIdIndexRoute
  AuthedOrgsOrgIdIntegrationsGithubRoute: typeof AuthedOrgsOrgIdIntegrationsGithubRoute
  AuthedOrgsOrgIdIntegrationsSlackRoute: typeof AuthedOrgsOrgIdIntegrationsSlackRoute
  AuthedOrgsOrgIdProjectsProjectIdRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren
  AuthedOrgsOrgIdIntegrationsIndexRoute: typeof AuthedOrgsOrgIdIntegrationsIndexRoute
  AuthedOrgsOrgIdProjectsIndexRoute: typeof AuthedOrgsOrgIdProjectsIndexRoute
}

const AuthedOrgsOrgIdRouteChildren: AuthedOrgsOrgIdRouteChildren = {
  AuthedOrgsOrgIdBillingRoute: AuthedOrgsOrgIdBillingRoute,
  AuthedOrgsOrgIdKeysRoute: AuthedOrgsOrgIdKeysRouteWithChildren,
  AuthedOrgsOrgIdSettingsRoute: AuthedOrgsOrgIdSettingsRouteWithChildren,
  AuthedOrgsOrgIdIndexRoute: AuthedOrgsOrgIdIndexRoute,
  AuthedOrgsOrgIdIntegrationsGithubRoute:
    AuthedOrgsOrgIdIntegrationsGithubRoute,
  AuthedOrgsOrgIdIntegrationsSlackRoute: AuthedOrgsOrgIdIntegrationsSlackRoute,
  AuthedOrgsOrgIdProjectsProjectIdRoute:
    AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren,
  AuthedOrgsOrgIdIntegrationsIndexRoute: AuthedOrgsOrgIdIntegrationsIndexRoute,
  AuthedOrgsOrgIdProjectsIndexRoute: AuthedOrgsOrgIdProjectsIndexRoute,
}

const AuthedOrgsOrgIdRouteWithChildren = AuthedOrgsOrgIdRoute._addFileChildren(
  AuthedOrgsOrgIdRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRouteWithChildren
  AuthedOrgsOrgIdRoute: typeof AuthedOrgsOrgIdRouteWithChildren
  AuthedRRunIdRoute: typeof AuthedRRunIdRoute
  AuthedOrgsIndexRoute: typeof AuthedOrgsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedProfileRoute: AuthedProfileRouteWithChildren,
  AuthedOrgsOrgIdRoute: AuthedOrgsOrgIdRouteWithChildren,
  AuthedRRunIdRoute: AuthedRRunIdRoute,
  AuthedOrgsIndexRoute: AuthedOrgsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface MarketingRouteRouteChildren {
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingSecurityRoute: typeof MarketingSecurityRoute
  MarketingSupportRoute: typeof MarketingSupportRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingCompareAllureRoute: typeof MarketingCompareAllureRoute
  MarketingCompareDatadogRoute: typeof MarketingCompareDatadogRoute
  MarketingCompareReportportalRoute: typeof MarketingCompareReportportalRoute
  MarketingCompareTestrailRoute: typeof MarketingCompareTestrailRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingSecurityRoute: MarketingSecurityRoute,
  MarketingSupportRoute: MarketingSupportRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingCompareAllureRoute: MarketingCompareAllureRoute,
  MarketingCompareDatadogRoute: MarketingCompareDatadogRoute,
  MarketingCompareReportportalRoute: MarketingCompareReportportalRoute,
  MarketingCompareTestrailRoute: MarketingCompareTestrailRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
