/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedOrgsIndexRouteImport } from './routes/_authed/orgs.index'
import { Route as AuthedOrgsOrgIdRouteImport } from './routes/_authed/orgs.$orgId'
import { Route as AuthedOrgsOrgIdIndexRouteImport } from './routes/_authed/orgs.$orgId.index'
import { Route as AuthedOrgsOrgIdUsersRouteImport } from './routes/_authed/orgs.$orgId.users'
import { Route as AuthedOrgsOrgIdSettingsRouteImport } from './routes/_authed/orgs.$orgId.settings'
import { Route as AuthedOrgsOrgIdKeysRouteImport } from './routes/_authed/orgs.$orgId.keys'
import { Route as AuthedOrgsOrgIdBillingRouteImport } from './routes/_authed/orgs.$orgId.billing'
import { Route as AuthedOrgsOrgIdProjectsIndexRouteImport } from './routes/_authed/orgs.$orgId.projects.index'
import { Route as AuthedOrgsOrgIdKeysIndexRouteImport } from './routes/_authed/orgs.$orgId.keys.index'
import { Route as AuthedOrgsOrgIdIntegrationsIndexRouteImport } from './routes/_authed/orgs.$orgId.integrations.index'
import { Route as AuthedOrgsOrgIdProjectsProjectIdRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId'
import { Route as AuthedOrgsOrgIdKeysMcpRouteImport } from './routes/_authed/orgs.$orgId.keys.mcp'
import { Route as AuthedOrgsOrgIdKeysIngestionRouteImport } from './routes/_authed/orgs.$orgId.keys.ingestion'
import { Route as AuthedOrgsOrgIdIntegrationsSlackRouteImport } from './routes/_authed/orgs.$orgId.integrations.slack'
import { Route as AuthedOrgsOrgIdIntegrationsGithubRouteImport } from './routes/_authed/orgs.$orgId.integrations.github'
import { Route as AuthedOrgsOrgIdProjectsProjectIdIndexRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.index'
import { Route as AuthedOrgsOrgIdProjectsProjectIdSettingsRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.settings'
import { Route as AuthedOrgsOrgIdProjectsProjectIdFlakyRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.flaky'
import { Route as AuthedOrgsOrgIdProjectsProjectIdExplorerRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.explorer'
import { Route as AuthedOrgsOrgIdProjectsProjectIdRunsIndexRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.runs.index'
import { Route as AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.explorer_.$testId'
import { Route as AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.runs.$runId.index'
import { Route as AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRouteImport } from './routes/_authed/orgs.$orgId.projects.$projectId.runs.$runId.file'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgsIndexRoute = AuthedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrgsOrgIdRoute = AuthedOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrgsOrgIdIndexRoute = AuthedOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdUsersRoute = AuthedOrgsOrgIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdSettingsRoute = AuthedOrgsOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdKeysRoute = AuthedOrgsOrgIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdBillingRoute = AuthedOrgsOrgIdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdProjectsIndexRoute =
  AuthedOrgsOrgIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdKeysIndexRoute =
  AuthedOrgsOrgIdKeysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgIdKeysRoute,
  } as any)
const AuthedOrgsOrgIdIntegrationsIndexRoute =
  AuthedOrgsOrgIdIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdRoute =
  AuthedOrgsOrgIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdKeysMcpRoute = AuthedOrgsOrgIdKeysMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthedOrgsOrgIdKeysRoute,
} as any)
const AuthedOrgsOrgIdKeysIngestionRoute =
  AuthedOrgsOrgIdKeysIngestionRouteImport.update({
    id: '/ingestion',
    path: '/ingestion',
    getParentRoute: () => AuthedOrgsOrgIdKeysRoute,
  } as any)
const AuthedOrgsOrgIdIntegrationsSlackRoute =
  AuthedOrgsOrgIdIntegrationsSlackRouteImport.update({
    id: '/integrations/slack',
    path: '/integrations/slack',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdIntegrationsGithubRoute =
  AuthedOrgsOrgIdIntegrationsGithubRouteImport.update({
    id: '/integrations/github',
    path: '/integrations/github',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdIndexRoute =
  AuthedOrgsOrgIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdSettingsRoute =
  AuthedOrgsOrgIdProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdFlakyRoute =
  AuthedOrgsOrgIdProjectsProjectIdFlakyRouteImport.update({
    id: '/flaky',
    path: '/flaky',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdExplorerRoute =
  AuthedOrgsOrgIdProjectsProjectIdExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute =
  AuthedOrgsOrgIdProjectsProjectIdRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute =
  AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRouteImport.update({
    id: '/explorer_/$testId',
    path: '/explorer/$testId',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute =
  AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRouteImport.update({
    id: '/runs/$runId/',
    path: '/runs/$runId/',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute =
  AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRouteImport.update({
    id: '/runs/$runId/file',
    path: '/runs/$runId/file',
    getParentRoute: () => AuthedOrgsOrgIdProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/orgs/$orgId': typeof AuthedOrgsOrgIdRouteWithChildren
  '/orgs/': typeof AuthedOrgsIndexRoute
  '/orgs/$orgId/billing': typeof AuthedOrgsOrgIdBillingRoute
  '/orgs/$orgId/keys': typeof AuthedOrgsOrgIdKeysRouteWithChildren
  '/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsRoute
  '/orgs/$orgId/users': typeof AuthedOrgsOrgIdUsersRoute
  '/orgs/$orgId/': typeof AuthedOrgsOrgIdIndexRoute
  '/orgs/$orgId/integrations/github': typeof AuthedOrgsOrgIdIntegrationsGithubRoute
  '/orgs/$orgId/integrations/slack': typeof AuthedOrgsOrgIdIntegrationsSlackRoute
  '/orgs/$orgId/keys/ingestion': typeof AuthedOrgsOrgIdKeysIngestionRoute
  '/orgs/$orgId/keys/mcp': typeof AuthedOrgsOrgIdKeysMcpRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren
  '/orgs/$orgId/integrations/': typeof AuthedOrgsOrgIdIntegrationsIndexRoute
  '/orgs/$orgId/keys/': typeof AuthedOrgsOrgIdKeysIndexRoute
  '/orgs/$orgId/projects/': typeof AuthedOrgsOrgIdProjectsIndexRoute
  '/orgs/$orgId/projects/$projectId/explorer': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRoute
  '/orgs/$orgId/projects/$projectId/flaky': typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRoute
  '/orgs/$orgId/projects/$projectId/settings': typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/orgs/$orgId/projects/$projectId/': typeof AuthedOrgsOrgIdProjectsProjectIdIndexRoute
  '/orgs/$orgId/projects/$projectId/explorer/$testId': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute
  '/orgs/$orgId/projects/$projectId/runs/': typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute
  '/orgs/$orgId/projects/$projectId/runs/$runId/file': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute
  '/orgs/$orgId/projects/$projectId/runs/$runId/': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/orgs': typeof AuthedOrgsIndexRoute
  '/orgs/$orgId/billing': typeof AuthedOrgsOrgIdBillingRoute
  '/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsRoute
  '/orgs/$orgId/users': typeof AuthedOrgsOrgIdUsersRoute
  '/orgs/$orgId': typeof AuthedOrgsOrgIdIndexRoute
  '/orgs/$orgId/integrations/github': typeof AuthedOrgsOrgIdIntegrationsGithubRoute
  '/orgs/$orgId/integrations/slack': typeof AuthedOrgsOrgIdIntegrationsSlackRoute
  '/orgs/$orgId/keys/ingestion': typeof AuthedOrgsOrgIdKeysIngestionRoute
  '/orgs/$orgId/keys/mcp': typeof AuthedOrgsOrgIdKeysMcpRoute
  '/orgs/$orgId/integrations': typeof AuthedOrgsOrgIdIntegrationsIndexRoute
  '/orgs/$orgId/keys': typeof AuthedOrgsOrgIdKeysIndexRoute
  '/orgs/$orgId/projects': typeof AuthedOrgsOrgIdProjectsIndexRoute
  '/orgs/$orgId/projects/$projectId/explorer': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRoute
  '/orgs/$orgId/projects/$projectId/flaky': typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRoute
  '/orgs/$orgId/projects/$projectId/settings': typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthedOrgsOrgIdProjectsProjectIdIndexRoute
  '/orgs/$orgId/projects/$projectId/explorer/$testId': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute
  '/orgs/$orgId/projects/$projectId/runs': typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute
  '/orgs/$orgId/projects/$projectId/runs/$runId/file': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute
  '/orgs/$orgId/projects/$projectId/runs/$runId': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/_authed/orgs/$orgId': typeof AuthedOrgsOrgIdRouteWithChildren
  '/_authed/orgs/': typeof AuthedOrgsIndexRoute
  '/_authed/orgs/$orgId/billing': typeof AuthedOrgsOrgIdBillingRoute
  '/_authed/orgs/$orgId/keys': typeof AuthedOrgsOrgIdKeysRouteWithChildren
  '/_authed/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsRoute
  '/_authed/orgs/$orgId/users': typeof AuthedOrgsOrgIdUsersRoute
  '/_authed/orgs/$orgId/': typeof AuthedOrgsOrgIdIndexRoute
  '/_authed/orgs/$orgId/integrations/github': typeof AuthedOrgsOrgIdIntegrationsGithubRoute
  '/_authed/orgs/$orgId/integrations/slack': typeof AuthedOrgsOrgIdIntegrationsSlackRoute
  '/_authed/orgs/$orgId/keys/ingestion': typeof AuthedOrgsOrgIdKeysIngestionRoute
  '/_authed/orgs/$orgId/keys/mcp': typeof AuthedOrgsOrgIdKeysMcpRoute
  '/_authed/orgs/$orgId/projects/$projectId': typeof AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren
  '/_authed/orgs/$orgId/integrations/': typeof AuthedOrgsOrgIdIntegrationsIndexRoute
  '/_authed/orgs/$orgId/keys/': typeof AuthedOrgsOrgIdKeysIndexRoute
  '/_authed/orgs/$orgId/projects/': typeof AuthedOrgsOrgIdProjectsIndexRoute
  '/_authed/orgs/$orgId/projects/$projectId/explorer': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRoute
  '/_authed/orgs/$orgId/projects/$projectId/flaky': typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRoute
  '/_authed/orgs/$orgId/projects/$projectId/settings': typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/_authed/orgs/$orgId/projects/$projectId/': typeof AuthedOrgsOrgIdProjectsProjectIdIndexRoute
  '/_authed/orgs/$orgId/projects/$projectId/explorer_/$testId': typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute
  '/_authed/orgs/$orgId/projects/$projectId/runs/': typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute
  '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/file': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute
  '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/': typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms'
    | '/verify'
    | '/orgs/$orgId'
    | '/orgs/'
    | '/orgs/$orgId/billing'
    | '/orgs/$orgId/keys'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/users'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/integrations/github'
    | '/orgs/$orgId/integrations/slack'
    | '/orgs/$orgId/keys/ingestion'
    | '/orgs/$orgId/keys/mcp'
    | '/orgs/$orgId/projects/$projectId'
    | '/orgs/$orgId/integrations/'
    | '/orgs/$orgId/keys/'
    | '/orgs/$orgId/projects/'
    | '/orgs/$orgId/projects/$projectId/explorer'
    | '/orgs/$orgId/projects/$projectId/flaky'
    | '/orgs/$orgId/projects/$projectId/settings'
    | '/orgs/$orgId/projects/$projectId/'
    | '/orgs/$orgId/projects/$projectId/explorer/$testId'
    | '/orgs/$orgId/projects/$projectId/runs/'
    | '/orgs/$orgId/projects/$projectId/runs/$runId/file'
    | '/orgs/$orgId/projects/$projectId/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms'
    | '/verify'
    | '/orgs'
    | '/orgs/$orgId/billing'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/users'
    | '/orgs/$orgId'
    | '/orgs/$orgId/integrations/github'
    | '/orgs/$orgId/integrations/slack'
    | '/orgs/$orgId/keys/ingestion'
    | '/orgs/$orgId/keys/mcp'
    | '/orgs/$orgId/integrations'
    | '/orgs/$orgId/keys'
    | '/orgs/$orgId/projects'
    | '/orgs/$orgId/projects/$projectId/explorer'
    | '/orgs/$orgId/projects/$projectId/flaky'
    | '/orgs/$orgId/projects/$projectId/settings'
    | '/orgs/$orgId/projects/$projectId'
    | '/orgs/$orgId/projects/$projectId/explorer/$testId'
    | '/orgs/$orgId/projects/$projectId/runs'
    | '/orgs/$orgId/projects/$projectId/runs/$runId/file'
    | '/orgs/$orgId/projects/$projectId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms'
    | '/verify'
    | '/_authed/orgs/$orgId'
    | '/_authed/orgs/'
    | '/_authed/orgs/$orgId/billing'
    | '/_authed/orgs/$orgId/keys'
    | '/_authed/orgs/$orgId/settings'
    | '/_authed/orgs/$orgId/users'
    | '/_authed/orgs/$orgId/'
    | '/_authed/orgs/$orgId/integrations/github'
    | '/_authed/orgs/$orgId/integrations/slack'
    | '/_authed/orgs/$orgId/keys/ingestion'
    | '/_authed/orgs/$orgId/keys/mcp'
    | '/_authed/orgs/$orgId/projects/$projectId'
    | '/_authed/orgs/$orgId/integrations/'
    | '/_authed/orgs/$orgId/keys/'
    | '/_authed/orgs/$orgId/projects/'
    | '/_authed/orgs/$orgId/projects/$projectId/explorer'
    | '/_authed/orgs/$orgId/projects/$projectId/flaky'
    | '/_authed/orgs/$orgId/projects/$projectId/settings'
    | '/_authed/orgs/$orgId/projects/$projectId/'
    | '/_authed/orgs/$orgId/projects/$projectId/explorer_/$testId'
    | '/_authed/orgs/$orgId/projects/$projectId/runs/'
    | '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/file'
    | '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/orgs/': {
      id: '/_authed/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthedOrgsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orgs/$orgId': {
      id: '/_authed/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthedOrgsOrgIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orgs/$orgId/': {
      id: '/_authed/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/users': {
      id: '/_authed/orgs/$orgId/users'
      path: '/users'
      fullPath: '/orgs/$orgId/users'
      preLoaderRoute: typeof AuthedOrgsOrgIdUsersRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/settings': {
      id: '/_authed/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthedOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/keys': {
      id: '/_authed/orgs/$orgId/keys'
      path: '/keys'
      fullPath: '/orgs/$orgId/keys'
      preLoaderRoute: typeof AuthedOrgsOrgIdKeysRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/billing': {
      id: '/_authed/orgs/$orgId/billing'
      path: '/billing'
      fullPath: '/orgs/$orgId/billing'
      preLoaderRoute: typeof AuthedOrgsOrgIdBillingRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/projects/': {
      id: '/_authed/orgs/$orgId/projects/'
      path: '/projects'
      fullPath: '/orgs/$orgId/projects/'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/keys/': {
      id: '/_authed/orgs/$orgId/keys/'
      path: '/'
      fullPath: '/orgs/$orgId/keys/'
      preLoaderRoute: typeof AuthedOrgsOrgIdKeysIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdKeysRoute
    }
    '/_authed/orgs/$orgId/integrations/': {
      id: '/_authed/orgs/$orgId/integrations/'
      path: '/integrations'
      fullPath: '/orgs/$orgId/integrations/'
      preLoaderRoute: typeof AuthedOrgsOrgIdIntegrationsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId': {
      id: '/_authed/orgs/$orgId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/orgs/$orgId/projects/$projectId'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/keys/mcp': {
      id: '/_authed/orgs/$orgId/keys/mcp'
      path: '/mcp'
      fullPath: '/orgs/$orgId/keys/mcp'
      preLoaderRoute: typeof AuthedOrgsOrgIdKeysMcpRouteImport
      parentRoute: typeof AuthedOrgsOrgIdKeysRoute
    }
    '/_authed/orgs/$orgId/keys/ingestion': {
      id: '/_authed/orgs/$orgId/keys/ingestion'
      path: '/ingestion'
      fullPath: '/orgs/$orgId/keys/ingestion'
      preLoaderRoute: typeof AuthedOrgsOrgIdKeysIngestionRouteImport
      parentRoute: typeof AuthedOrgsOrgIdKeysRoute
    }
    '/_authed/orgs/$orgId/integrations/slack': {
      id: '/_authed/orgs/$orgId/integrations/slack'
      path: '/integrations/slack'
      fullPath: '/orgs/$orgId/integrations/slack'
      preLoaderRoute: typeof AuthedOrgsOrgIdIntegrationsSlackRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/integrations/github': {
      id: '/_authed/orgs/$orgId/integrations/github'
      path: '/integrations/github'
      fullPath: '/orgs/$orgId/integrations/github'
      preLoaderRoute: typeof AuthedOrgsOrgIdIntegrationsGithubRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/': {
      id: '/_authed/orgs/$orgId/projects/$projectId/'
      path: '/'
      fullPath: '/orgs/$orgId/projects/$projectId/'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/settings': {
      id: '/_authed/orgs/$orgId/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/flaky': {
      id: '/_authed/orgs/$orgId/projects/$projectId/flaky'
      path: '/flaky'
      fullPath: '/orgs/$orgId/projects/$projectId/flaky'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/explorer': {
      id: '/_authed/orgs/$orgId/projects/$projectId/explorer'
      path: '/explorer'
      fullPath: '/orgs/$orgId/projects/$projectId/explorer'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/runs/': {
      id: '/_authed/orgs/$orgId/projects/$projectId/runs/'
      path: '/runs'
      fullPath: '/orgs/$orgId/projects/$projectId/runs/'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/explorer_/$testId': {
      id: '/_authed/orgs/$orgId/projects/$projectId/explorer_/$testId'
      path: '/explorer/$testId'
      fullPath: '/orgs/$orgId/projects/$projectId/explorer/$testId'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/': {
      id: '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/'
      path: '/runs/$runId'
      fullPath: '/orgs/$orgId/projects/$projectId/runs/$runId/'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
    '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/file': {
      id: '/_authed/orgs/$orgId/projects/$projectId/runs/$runId/file'
      path: '/runs/$runId/file'
      fullPath: '/orgs/$orgId/projects/$projectId/runs/$runId/file'
      preLoaderRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRouteImport
      parentRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRoute
    }
  }
}

interface AuthedOrgsOrgIdKeysRouteChildren {
  AuthedOrgsOrgIdKeysIngestionRoute: typeof AuthedOrgsOrgIdKeysIngestionRoute
  AuthedOrgsOrgIdKeysMcpRoute: typeof AuthedOrgsOrgIdKeysMcpRoute
  AuthedOrgsOrgIdKeysIndexRoute: typeof AuthedOrgsOrgIdKeysIndexRoute
}

const AuthedOrgsOrgIdKeysRouteChildren: AuthedOrgsOrgIdKeysRouteChildren = {
  AuthedOrgsOrgIdKeysIngestionRoute: AuthedOrgsOrgIdKeysIngestionRoute,
  AuthedOrgsOrgIdKeysMcpRoute: AuthedOrgsOrgIdKeysMcpRoute,
  AuthedOrgsOrgIdKeysIndexRoute: AuthedOrgsOrgIdKeysIndexRoute,
}

const AuthedOrgsOrgIdKeysRouteWithChildren =
  AuthedOrgsOrgIdKeysRoute._addFileChildren(AuthedOrgsOrgIdKeysRouteChildren)

interface AuthedOrgsOrgIdProjectsProjectIdRouteChildren {
  AuthedOrgsOrgIdProjectsProjectIdExplorerRoute: typeof AuthedOrgsOrgIdProjectsProjectIdExplorerRoute
  AuthedOrgsOrgIdProjectsProjectIdFlakyRoute: typeof AuthedOrgsOrgIdProjectsProjectIdFlakyRoute
  AuthedOrgsOrgIdProjectsProjectIdSettingsRoute: typeof AuthedOrgsOrgIdProjectsProjectIdSettingsRoute
  AuthedOrgsOrgIdProjectsProjectIdIndexRoute: typeof AuthedOrgsOrgIdProjectsProjectIdIndexRoute
  AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute: typeof AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute
  AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute
  AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute
  AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute
}

const AuthedOrgsOrgIdProjectsProjectIdRouteChildren: AuthedOrgsOrgIdProjectsProjectIdRouteChildren =
  {
    AuthedOrgsOrgIdProjectsProjectIdExplorerRoute:
      AuthedOrgsOrgIdProjectsProjectIdExplorerRoute,
    AuthedOrgsOrgIdProjectsProjectIdFlakyRoute:
      AuthedOrgsOrgIdProjectsProjectIdFlakyRoute,
    AuthedOrgsOrgIdProjectsProjectIdSettingsRoute:
      AuthedOrgsOrgIdProjectsProjectIdSettingsRoute,
    AuthedOrgsOrgIdProjectsProjectIdIndexRoute:
      AuthedOrgsOrgIdProjectsProjectIdIndexRoute,
    AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute:
      AuthedOrgsOrgIdProjectsProjectIdExplorerTestIdRoute,
    AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute:
      AuthedOrgsOrgIdProjectsProjectIdRunsIndexRoute,
    AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute:
      AuthedOrgsOrgIdProjectsProjectIdRunsRunIdFileRoute,
    AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute:
      AuthedOrgsOrgIdProjectsProjectIdRunsRunIdIndexRoute,
  }

const AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren =
  AuthedOrgsOrgIdProjectsProjectIdRoute._addFileChildren(
    AuthedOrgsOrgIdProjectsProjectIdRouteChildren,
  )

interface AuthedOrgsOrgIdRouteChildren {
  AuthedOrgsOrgIdBillingRoute: typeof AuthedOrgsOrgIdBillingRoute
  AuthedOrgsOrgIdKeysRoute: typeof AuthedOrgsOrgIdKeysRouteWithChildren
  AuthedOrgsOrgIdSettingsRoute: typeof AuthedOrgsOrgIdSettingsRoute
  AuthedOrgsOrgIdUsersRoute: typeof AuthedOrgsOrgIdUsersRoute
  AuthedOrgsOrgIdIndexRoute: typeof AuthedOrgsOrgIdIndexRoute
  AuthedOrgsOrgIdIntegrationsGithubRoute: typeof AuthedOrgsOrgIdIntegrationsGithubRoute
  AuthedOrgsOrgIdIntegrationsSlackRoute: typeof AuthedOrgsOrgIdIntegrationsSlackRoute
  AuthedOrgsOrgIdProjectsProjectIdRoute: typeof AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren
  AuthedOrgsOrgIdIntegrationsIndexRoute: typeof AuthedOrgsOrgIdIntegrationsIndexRoute
  AuthedOrgsOrgIdProjectsIndexRoute: typeof AuthedOrgsOrgIdProjectsIndexRoute
}

const AuthedOrgsOrgIdRouteChildren: AuthedOrgsOrgIdRouteChildren = {
  AuthedOrgsOrgIdBillingRoute: AuthedOrgsOrgIdBillingRoute,
  AuthedOrgsOrgIdKeysRoute: AuthedOrgsOrgIdKeysRouteWithChildren,
  AuthedOrgsOrgIdSettingsRoute: AuthedOrgsOrgIdSettingsRoute,
  AuthedOrgsOrgIdUsersRoute: AuthedOrgsOrgIdUsersRoute,
  AuthedOrgsOrgIdIndexRoute: AuthedOrgsOrgIdIndexRoute,
  AuthedOrgsOrgIdIntegrationsGithubRoute:
    AuthedOrgsOrgIdIntegrationsGithubRoute,
  AuthedOrgsOrgIdIntegrationsSlackRoute: AuthedOrgsOrgIdIntegrationsSlackRoute,
  AuthedOrgsOrgIdProjectsProjectIdRoute:
    AuthedOrgsOrgIdProjectsProjectIdRouteWithChildren,
  AuthedOrgsOrgIdIntegrationsIndexRoute: AuthedOrgsOrgIdIntegrationsIndexRoute,
  AuthedOrgsOrgIdProjectsIndexRoute: AuthedOrgsOrgIdProjectsIndexRoute,
}

const AuthedOrgsOrgIdRouteWithChildren = AuthedOrgsOrgIdRoute._addFileChildren(
  AuthedOrgsOrgIdRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedOrgsOrgIdRoute: typeof AuthedOrgsOrgIdRouteWithChildren
  AuthedOrgsIndexRoute: typeof AuthedOrgsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedOrgsOrgIdRoute: AuthedOrgsOrgIdRouteWithChildren,
  AuthedOrgsIndexRoute: AuthedOrgsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
