// This file is auto-generated by @hey-api/openapi-ts

export type UserMinimal = {
    id: string;
    email: string;
};

export type SignupResponse = {
    user: UserMinimal;
};

export type ApiError = {
    error: {
        code: string;
        message: string;
        field?: string;
        details?: unknown;
    };
};

export type SignupBody = {
    email: string;
    password: string;
    name?: string;
};

export type UserPublic = {
    id: string;
    email: string;
    name: string | null;
    emailVerifiedAt: string | null;
    hasAvatar: boolean;
    avatarUpdatedAt: string | null;
    createdAt: string;
};

export type UserResponse = {
    user: UserPublic;
};

export type LoginBody = {
    email: string;
    password: string;
};

export type VerifiedResponse = {
    verified: true;
};

export type VerifyEmailBody = {
    token: string;
};

export type ResendVerificationBody = {
    email: string;
};

export type ForgotPasswordBody = {
    email: string;
};

export type ResetResponse = {
    reset: true;
};

export type ResetPasswordBody = {
    token: string;
    password: string;
};

export type UpdateMeBody = {
    name?: string | null;
};

export type OrgSummary = {
    id: string;
    name: string;
    hasLogo: boolean;
    logoUpdatedAt: string | null;
};

export type OrgListResponse = {
    orgs: Array<OrgSummary>;
};

export type OrgResponse = {
    id: string;
    name: string;
    description: string | null;
    website: string | null;
    contactEmail: string | null;
    hasLogo: boolean;
    logoUpdatedAt: string | null;
};

export type CreateOrgBody = {
    name: string;
    description?: string;
    website?: string;
    contactEmail?: string;
};

export type UpdateOrgBody = {
    name: string;
    description?: string;
    website?: string;
    contactEmail?: string;
};

export type MemberSummary = {
    userId: string;
    email: string;
    name: string | null;
    hasAvatar: boolean;
    avatarUpdatedAt: string | null;
    joinedAt: string;
};

export type MemberListResponse = {
    members: Array<MemberSummary>;
};

export type OkResponse = {
    ok: boolean;
};

export type InvitationSummary = {
    id: string;
    email: string;
    invitedAt: string;
    expiresAt: string;
    status: 'pending' | 'expired';
};

export type InvitationListResponse = {
    invitations: Array<InvitationSummary>;
};

export type CreateInviteBody = {
    email: string;
};

export type InvitePreviewResponse = {
    orgId: string;
    orgName: string;
    email: string;
    status: 'pending' | 'expired' | 'accepted';
};

export type AcceptInviteResponse = {
    orgId: string;
    orgName: string;
};

export type ProjectStats = {
    status: 'pass' | 'fail' | 'flaky';
    passRate: number;
    runCount: number;
    testsCount: number;
    flakyCount: number;
    avgDurationSec: number | null;
    lastRunAt: string;
    ciProvider: string | null;
} | null;

export type RunBar = {
    startedAt: string;
    total: number;
    passed: number;
    failed: number;
    flaky: number;
    durationSec: number | null;
    commitSha: string | null;
    branch: string | null;
};

export type ProjectSummary = {
    id: string;
    name: string;
    description: string | null;
    repositoryUrl: string | null;
    defaultBranch: string | null;
    icon: string | null;
    color: string | null;
    createdAt: string;
    stats: ProjectStats;
    chartRuns: Array<RunBar>;
};

export type CreateProjectBody = {
    name: string;
    description?: string;
    repositoryUrl?: string;
    defaultBranch?: string;
    icon?: 'layers' | 'flask' | 'git' | 'code' | 'docs' | 'flow' | 'pulse' | 'home';
    color?: 'emerald' | 'indigo' | 'amber' | 'sky' | 'pink' | 'teal';
};

export type ProjectListResponse = {
    projects: Array<ProjectSummary>;
};

export type UpdateProjectBody = {
    name: string;
    description?: string;
    repositoryUrl?: string;
    defaultBranch?: string;
    icon?: 'layers' | 'flask' | 'git' | 'code' | 'docs' | 'flow' | 'pulse' | 'home';
    color?: 'emerald' | 'indigo' | 'amber' | 'sky' | 'pink' | 'teal';
};

export type ProjectDeletedResponse = {
    ok: true;
};

export type RunCreatedResponse = {
    id: string;
};

export type CreateRunBody = {
    projectId: string;
    environment?: string;
    startedAt: string;
    commitSha?: string;
    branch?: string;
    prNumber?: number;
    repository?: string;
    authorEmail?: string;
    authorName?: string;
    ciProvider?: string;
    ciRunId?: string;
    ciRunUrl?: string;
};

export type FinalizeRunBody = {
    status: 'passed' | 'failed' | 'timedout' | 'interrupted';
    finishedAt: string;
    stats: {
        total: number;
        passed: number;
        failed: number;
        skipped: number;
        flaky: number;
    };
};

export type CreateExecutionsBody = {
    executions: Array<{
        id: string;
        testId: string;
        title: string;
        titlePath: Array<string>;
        file: string;
        projectName?: string;
        status: 'passed' | 'failed' | 'timedOut' | 'skipped' | 'interrupted';
        durationMs: number;
        retry: number;
        errorMessage?: string;
        startedAt: string;
    }>;
};

export type ArtifactUploadedResponse = {
    id: string;
    kind: 'trace' | 'screenshot' | 'video';
    sizeBytes: number;
};

export type RunFiltersResponse = {
    branches: Array<string>;
    users: Array<{
        email: string;
        name: string | null;
    }>;
};

export type RunSummary = {
    id: string;
    projectId: string;
    projectName: string;
    status: string;
    environment: string | null;
    commitSha: string | null;
    branch: string | null;
    prNumber: number | null;
    repository: string | null;
    authorEmail: string | null;
    authorName: string | null;
    ciProvider: string | null;
    ciRunId: string | null;
    ciRunUrl: string | null;
    startedAt: string;
    finishedAt: string | null;
    stats: {
        total: number;
        passed: number;
        failed: number;
        skipped: number;
        flaky: number;
    } | null;
    createdAt: string;
};

export type RunListResponse = {
    runs: Array<RunSummary>;
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
};

export type RunAggregate = {
    total: number;
    passed: number;
    failed: number;
    flaky: number;
    skipped: number;
    durationSec: number | null;
};

export type RunFileSummary = {
    file: string;
    total: number;
    passed: number;
    failed: number;
    flaky: number;
    skipped: number;
};

export type RunDetailResponse = {
    run: RunSummary;
    summary: RunAggregate;
    files: Array<RunFileSummary>;
};

export type ArtifactSummary = {
    id: string;
    kind: 'trace' | 'screenshot' | 'video';
    contentType: string;
    sizeBytes: number;
    name: string | null;
    url: string | null;
};

export type AttemptSummary = {
    id: string;
    retry: number;
    status: string;
    durationMs: number;
    errorMessage: string | null;
    startedAt: string;
    artifacts: Array<ArtifactSummary>;
};

export type TestCase = {
    testId: string;
    title: string;
    titlePath: Array<string>;
    status: 'passed' | 'failed' | 'flaky' | 'skipped';
    attempts: Array<AttemptSummary>;
};

export type RunFileTestsResponse = {
    file: string;
    tests: Array<TestCase>;
};

export type ArtifactUrlResponse = {
    url: string;
};

export type SecretKeySummary = {
    id: string;
    name: string;
    scope: 'org' | 'project';
    prefix: string;
    last4: string;
    project: {
        id: string;
        name: string;
        icon: string | null;
        color: string | null;
    } | null;
    createdAt: string;
    lastUsedAt: string | null;
};

export type SecretKeyListResponse = {
    keys: Array<SecretKeySummary>;
};

export type SecretKeyCreatedResponse = {
    id: string;
    name: string;
    scope: 'org' | 'project';
    prefix: string;
    last4: string;
    project: {
        id: string;
        name: string;
        icon: string | null;
        color: string | null;
    } | null;
    createdAt: string;
    lastUsedAt: string | null;
    token: string;
};

export type CreateSecretKeyBody = {
    name: string;
    scope: 'org' | 'project';
    projectId?: string;
};

export type SecretKeyDeletedResponse = {
    ok: true;
};

export type SignupData = {
    body?: SignupBody;
    path?: never;
    query?: never;
    url: '/v1/auth/signup';
};

export type SignupErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Email exists
     */
    409: ApiError;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * Created
     */
    201: SignupResponse;
};

export type SignupResponse2 = SignupResponses[keyof SignupResponses];

export type LoginData = {
    body?: LoginBody;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid credentials or unverified email
     */
    401: ApiError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/logout';
};

export type LogoutErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type VerifyEmailData = {
    body?: VerifyEmailBody;
    path?: never;
    query?: never;
    url: '/v1/auth/verify-email';
};

export type VerifyEmailErrors = {
    /**
     * Invalid, expired, or used token
     */
    400: ApiError;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * Verified
     */
    200: VerifiedResponse;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type ResendVerificationData = {
    body?: ResendVerificationBody;
    path?: never;
    query?: never;
    url: '/v1/auth/resend-verification';
};

export type ResendVerificationResponses = {
    /**
     * Accepted
     */
    204: void;
};

export type ResendVerificationResponse = ResendVerificationResponses[keyof ResendVerificationResponses];

export type ForgotPasswordData = {
    body?: ForgotPasswordBody;
    path?: never;
    query?: never;
    url: '/v1/auth/forgot-password';
};

export type ForgotPasswordResponses = {
    /**
     * Accepted
     */
    204: void;
};

export type ForgotPasswordResponse = ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type ResetPasswordData = {
    body?: ResetPasswordBody;
    path?: never;
    query?: never;
    url: '/v1/auth/reset-password';
};

export type ResetPasswordErrors = {
    /**
     * Invalid, expired, or used token
     */
    400: ApiError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Password reset
     */
    200: ResetResponse;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/me';
};

export type GetMeErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateMeData = {
    body?: UpdateMeBody;
    path?: never;
    query?: never;
    url: '/v1/auth/me';
};

export type UpdateMeErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type DeleteMyAvatarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/me/avatar';
};

export type DeleteMyAvatarErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type DeleteMyAvatarError = DeleteMyAvatarErrors[keyof DeleteMyAvatarErrors];

export type DeleteMyAvatarResponses = {
    /**
     * Removed
     */
    200: UserResponse;
};

export type DeleteMyAvatarResponse = DeleteMyAvatarResponses[keyof DeleteMyAvatarResponses];

export type UploadMyAvatarData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/me/avatar';
};

export type UploadMyAvatarErrors = {
    /**
     * No file
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Image too large
     */
    413: ApiError;
    /**
     * Unsupported image type
     */
    415: ApiError;
    /**
     * Storage failure
     */
    502: ApiError;
};

export type UploadMyAvatarError = UploadMyAvatarErrors[keyof UploadMyAvatarErrors];

export type UploadMyAvatarResponses = {
    /**
     * Stored
     */
    200: UserResponse;
};

export type UploadMyAvatarResponse = UploadMyAvatarResponses[keyof UploadMyAvatarResponses];

export type ListOrgsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/orgs';
};

export type ListOrgsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type ListOrgsError = ListOrgsErrors[keyof ListOrgsErrors];

export type ListOrgsResponses = {
    /**
     * OK
     */
    200: OrgListResponse;
};

export type ListOrgsResponse = ListOrgsResponses[keyof ListOrgsResponses];

export type CreateOrgData = {
    body?: CreateOrgBody;
    path?: never;
    query?: never;
    url: '/v1/orgs';
};

export type CreateOrgErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type CreateOrgError = CreateOrgErrors[keyof CreateOrgErrors];

export type CreateOrgResponses = {
    /**
     * Created
     */
    201: OrgResponse;
};

export type CreateOrgResponse = CreateOrgResponses[keyof CreateOrgResponses];

export type GetOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}';
};

export type GetOrgErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type GetOrgError = GetOrgErrors[keyof GetOrgErrors];

export type GetOrgResponses = {
    /**
     * OK
     */
    200: OrgResponse;
};

export type GetOrgResponse = GetOrgResponses[keyof GetOrgResponses];

export type UpdateOrgData = {
    body?: UpdateOrgBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}';
};

export type UpdateOrgErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type UpdateOrgError = UpdateOrgErrors[keyof UpdateOrgErrors];

export type UpdateOrgResponses = {
    /**
     * OK
     */
    200: OrgResponse;
};

export type UpdateOrgResponse = UpdateOrgResponses[keyof UpdateOrgResponses];

export type DeleteOrgLogoData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/logo';
};

export type DeleteOrgLogoErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type DeleteOrgLogoError = DeleteOrgLogoErrors[keyof DeleteOrgLogoErrors];

export type DeleteOrgLogoResponses = {
    /**
     * Removed
     */
    200: OrgResponse;
};

export type DeleteOrgLogoResponse = DeleteOrgLogoResponses[keyof DeleteOrgLogoResponses];

export type UploadOrgLogoData = {
    body?: {
        file?: Blob | File;
    };
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/logo';
};

export type UploadOrgLogoErrors = {
    /**
     * No file
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
    /**
     * Logo too large
     */
    413: ApiError;
    /**
     * Unsupported image type
     */
    415: ApiError;
    /**
     * Storage failure
     */
    502: ApiError;
};

export type UploadOrgLogoError = UploadOrgLogoErrors[keyof UploadOrgLogoErrors];

export type UploadOrgLogoResponses = {
    /**
     * Stored
     */
    200: OrgResponse;
};

export type UploadOrgLogoResponse = UploadOrgLogoResponses[keyof UploadOrgLogoResponses];

export type ListOrgMembersData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/members';
};

export type ListOrgMembersErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type ListOrgMembersError = ListOrgMembersErrors[keyof ListOrgMembersErrors];

export type ListOrgMembersResponses = {
    /**
     * OK
     */
    200: MemberListResponse;
};

export type ListOrgMembersResponse = ListOrgMembersResponses[keyof ListOrgMembersResponses];

export type RemoveOrgMemberData = {
    body?: never;
    path: {
        orgId: string;
        userId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/members/{userId}';
};

export type RemoveOrgMemberErrors = {
    /**
     * Cannot remove self
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type RemoveOrgMemberError = RemoveOrgMemberErrors[keyof RemoveOrgMemberErrors];

export type RemoveOrgMemberResponses = {
    /**
     * Removed
     */
    200: OkResponse;
};

export type RemoveOrgMemberResponse = RemoveOrgMemberResponses[keyof RemoveOrgMemberResponses];

export type ListOrgInvitationsData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/invitations';
};

export type ListOrgInvitationsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type ListOrgInvitationsError = ListOrgInvitationsErrors[keyof ListOrgInvitationsErrors];

export type ListOrgInvitationsResponses = {
    /**
     * OK
     */
    200: InvitationListResponse;
};

export type ListOrgInvitationsResponse = ListOrgInvitationsResponses[keyof ListOrgInvitationsResponses];

export type CreateOrgInvitationData = {
    body?: CreateInviteBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/invitations';
};

export type CreateOrgInvitationErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
    /**
     * Already a member
     */
    409: ApiError;
};

export type CreateOrgInvitationError = CreateOrgInvitationErrors[keyof CreateOrgInvitationErrors];

export type CreateOrgInvitationResponses = {
    /**
     * Invitation sent
     */
    201: InvitationSummary;
};

export type CreateOrgInvitationResponse = CreateOrgInvitationResponses[keyof CreateOrgInvitationResponses];

export type RevokeOrgInvitationData = {
    body?: never;
    path: {
        orgId: string;
        invitationId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/invitations/{invitationId}';
};

export type RevokeOrgInvitationErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type RevokeOrgInvitationError = RevokeOrgInvitationErrors[keyof RevokeOrgInvitationErrors];

export type RevokeOrgInvitationResponses = {
    /**
     * Revoked
     */
    200: OkResponse;
};

export type RevokeOrgInvitationResponse = RevokeOrgInvitationResponses[keyof RevokeOrgInvitationResponses];

export type PreviewInvitationData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/v1/invitations/{token}';
};

export type PreviewInvitationErrors = {
    /**
     * Not found
     */
    404: ApiError;
};

export type PreviewInvitationError = PreviewInvitationErrors[keyof PreviewInvitationErrors];

export type PreviewInvitationResponses = {
    /**
     * OK
     */
    200: InvitePreviewResponse;
};

export type PreviewInvitationResponse = PreviewInvitationResponses[keyof PreviewInvitationResponses];

export type AcceptInvitationData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/v1/invitations/{token}/accept';
};

export type AcceptInvitationErrors = {
    /**
     * Expired
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Email mismatch
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type AcceptInvitationError = AcceptInvitationErrors[keyof AcceptInvitationErrors];

export type AcceptInvitationResponses = {
    /**
     * Joined
     */
    200: AcceptInviteResponse;
};

export type AcceptInvitationResponse = AcceptInvitationResponses[keyof AcceptInvitationResponses];

export type ListOrgProjectsData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/projects';
};

export type ListOrgProjectsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Org not found
     */
    404: ApiError;
};

export type ListOrgProjectsError = ListOrgProjectsErrors[keyof ListOrgProjectsErrors];

export type ListOrgProjectsResponses = {
    /**
     * OK
     */
    200: ProjectListResponse;
};

export type ListOrgProjectsResponse = ListOrgProjectsResponses[keyof ListOrgProjectsResponses];

export type CreateProjectData = {
    body?: CreateProjectBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/projects';
};

export type CreateProjectErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Org not found
     */
    404: ApiError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Created
     */
    201: ProjectSummary;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type DeleteProjectErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Deleted
     */
    200: ProjectDeletedResponse;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type GetProjectErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * OK
     */
    200: ProjectSummary;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body?: UpdateProjectBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type UpdateProjectErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * OK
     */
    200: ProjectSummary;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type CreateRunData = {
    body?: CreateRunBody;
    path?: never;
    query?: never;
    url: '/v1/runs';
};

export type CreateRunErrors = {
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type CreateRunError = CreateRunErrors[keyof CreateRunErrors];

export type CreateRunResponses = {
    /**
     * Created
     */
    201: RunCreatedResponse;
};

export type CreateRunResponse = CreateRunResponses[keyof CreateRunResponses];

export type GetRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}';
};

export type GetRunErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
};

export type GetRunError = GetRunErrors[keyof GetRunErrors];

export type GetRunResponses = {
    /**
     * OK
     */
    200: RunDetailResponse;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type FinalizeRunData = {
    body?: FinalizeRunBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}';
};

export type FinalizeRunErrors = {
    /**
     * Run not found
     */
    404: ApiError;
};

export type FinalizeRunError = FinalizeRunErrors[keyof FinalizeRunErrors];

export type FinalizeRunResponses = {
    /**
     * OK
     */
    200: OkResponse & {
        ok?: true;
    };
};

export type FinalizeRunResponse = FinalizeRunResponses[keyof FinalizeRunResponses];

export type CreateExecutionsData = {
    body?: CreateExecutionsBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}/executions';
};

export type CreateExecutionsErrors = {
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
};

export type CreateExecutionsError = CreateExecutionsErrors[keyof CreateExecutionsErrors];

export type CreateExecutionsResponses = {
    /**
     * OK
     */
    200: OkResponse & {
        ok?: true;
    };
};

export type CreateExecutionsResponse = CreateExecutionsResponses[keyof CreateExecutionsResponses];

export type UploadArtifactData = {
    body?: never;
    path: {
        id: string;
        eid: string;
        kind: 'trace' | 'screenshot' | 'video';
    };
    query?: never;
    url: '/v1/runs/{id}/executions/{eid}/artifacts/{kind}';
};

export type UploadArtifactErrors = {
    /**
     * Empty body
     */
    400: ApiError;
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Run/execution not found
     */
    404: ApiError;
    /**
     * Artifact too large
     */
    413: ApiError;
    /**
     * Storage failure
     */
    502: ApiError;
};

export type UploadArtifactError = UploadArtifactErrors[keyof UploadArtifactErrors];

export type UploadArtifactResponses = {
    /**
     * Stored
     */
    200: ArtifactUploadedResponse;
};

export type UploadArtifactResponse = UploadArtifactResponses[keyof UploadArtifactResponses];

export type GetProjectRunFiltersData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/v1/projects/{projectId}/runs/filters';
};

export type GetProjectRunFiltersErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type GetProjectRunFiltersError = GetProjectRunFiltersErrors[keyof GetProjectRunFiltersErrors];

export type GetProjectRunFiltersResponses = {
    /**
     * OK
     */
    200: RunFiltersResponse;
};

export type GetProjectRunFiltersResponse = GetProjectRunFiltersResponses[keyof GetProjectRunFiltersResponses];

export type ListProjectRunsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        status?: 'all' | 'passed' | 'failed' | 'flaky';
        branch?: string;
        user?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/v1/projects/{projectId}/runs';
};

export type ListProjectRunsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type ListProjectRunsError = ListProjectRunsErrors[keyof ListProjectRunsErrors];

export type ListProjectRunsResponses = {
    /**
     * OK
     */
    200: RunListResponse;
};

export type ListProjectRunsResponse = ListProjectRunsResponses[keyof ListProjectRunsResponses];

export type GetRunFileTestsData = {
    body?: never;
    path: {
        runId: string;
    };
    query: {
        file: string;
    };
    url: '/v1/runs/{runId}/tests';
};

export type GetRunFileTestsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
};

export type GetRunFileTestsError = GetRunFileTestsErrors[keyof GetRunFileTestsErrors];

export type GetRunFileTestsResponses = {
    /**
     * OK
     */
    200: RunFileTestsResponse;
};

export type GetRunFileTestsResponse = GetRunFileTestsResponses[keyof GetRunFileTestsResponses];

export type GetArtifactUrlData = {
    body?: never;
    path: {
        attachmentId: string;
    };
    query?: never;
    url: '/v1/attachments/{attachmentId}/url';
};

export type GetArtifactUrlErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type GetArtifactUrlError = GetArtifactUrlErrors[keyof GetArtifactUrlErrors];

export type GetArtifactUrlResponses = {
    /**
     * OK
     */
    200: ArtifactUrlResponse;
};

export type GetArtifactUrlResponse = GetArtifactUrlResponses[keyof GetArtifactUrlResponses];

export type ListSecretKeysData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/secret-keys';
};

export type ListSecretKeysErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Org not found
     */
    404: ApiError;
};

export type ListSecretKeysError = ListSecretKeysErrors[keyof ListSecretKeysErrors];

export type ListSecretKeysResponses = {
    /**
     * OK
     */
    200: SecretKeyListResponse;
};

export type ListSecretKeysResponse = ListSecretKeysResponses[keyof ListSecretKeysResponses];

export type CreateSecretKeyData = {
    body?: CreateSecretKeyBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/secret-keys';
};

export type CreateSecretKeyErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Org or project not found
     */
    404: ApiError;
};

export type CreateSecretKeyError = CreateSecretKeyErrors[keyof CreateSecretKeyErrors];

export type CreateSecretKeyResponses = {
    /**
     * Created
     */
    201: SecretKeyCreatedResponse;
};

export type CreateSecretKeyResponse = CreateSecretKeyResponses[keyof CreateSecretKeyResponses];

export type DeleteSecretKeyData = {
    body?: never;
    path: {
        orgId: string;
        keyId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/secret-keys/{keyId}';
};

export type DeleteSecretKeyErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type DeleteSecretKeyError = DeleteSecretKeyErrors[keyof DeleteSecretKeyErrors];

export type DeleteSecretKeyResponses = {
    /**
     * Revoked
     */
    200: SecretKeyDeletedResponse;
};

export type DeleteSecretKeyResponse = DeleteSecretKeyResponses[keyof DeleteSecretKeyResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};