// This file is auto-generated by @hey-api/openapi-ts

export type UserMinimal = {
    id: string;
    email: string;
};

export type SignupResponse = {
    user: UserMinimal;
};

export type ApiError = {
    error: {
        code: string;
        message: string;
        field?: string;
        details?: unknown;
    };
};

export type SignupBody = {
    email: string;
    password: string;
    name?: string;
};

export type UserPublic = {
    id: string;
    email: string;
    name: string | null;
    emailVerifiedAt: string | null;
    hasAvatar: boolean;
    avatarUpdatedAt: string | null;
    hasPassword: boolean;
    createdAt: string;
};

export type UserResponse = {
    user: UserPublic;
};

export type LoginBody = {
    email: string;
    password: string;
};

export type VerifiedResponse = {
    verified: true;
};

export type VerifyEmailBody = {
    token: string;
};

export type ResendVerificationBody = {
    email: string;
};

export type ForgotPasswordBody = {
    email: string;
};

export type ResetResponse = {
    reset: true;
};

export type ResetPasswordBody = {
    token: string;
    password: string;
};

export type OAuthAccountInfo = {
    provider: 'google' | 'github';
    email: string;
    createdAt: string;
};

export type OAuthAccountsResponse = {
    accounts: Array<OAuthAccountInfo>;
};

export type AuthOkResponse = {
    ok: true;
};

export type UpdatePasswordBody = {
    currentPassword?: string;
    newPassword: string;
};

export type UpdateMeBody = {
    name?: string | null;
};

export type OrgSummary = {
    id: string;
    name: string;
    role: 'admin' | 'member';
    hasLogo: boolean;
    logoUpdatedAt: string | null;
};

export type OrgListResponse = {
    orgs: Array<OrgSummary>;
};

export type OrgResponse = {
    id: string;
    name: string;
    description: string | null;
    website: string | null;
    contactEmail: string | null;
    role: 'admin' | 'member';
    hasLogo: boolean;
    logoUpdatedAt: string | null;
};

export type CreateOrgBody = {
    name: string;
    description?: string;
    website?: string;
    contactEmail?: string;
};

export type UpdateOrgBody = {
    name: string;
    description?: string;
    website?: string;
    contactEmail?: string;
};

export type OkResponse = {
    ok: boolean;
};

export type MemberSummary = {
    userId: string;
    email: string;
    name: string | null;
    role: 'admin' | 'member';
    hasAvatar: boolean;
    avatarUpdatedAt: string | null;
    joinedAt: string;
};

export type MemberListResponse = {
    members: Array<MemberSummary>;
};

export type UpdateMemberRoleBody = {
    role: 'admin' | 'member';
};

export type InvitationSummary = {
    id: string;
    email: string;
    invitedAt: string;
    expiresAt: string;
    status: 'pending' | 'expired';
};

export type InvitationListResponse = {
    invitations: Array<InvitationSummary>;
};

export type CreateInviteBody = {
    email: string;
    role?: 'admin' | 'member';
};

export type InvitePreviewResponse = {
    orgId: string;
    orgName: string;
    email: string;
    status: 'pending' | 'expired' | 'accepted';
};

export type AcceptInviteResponse = {
    orgId: string;
    orgName: string;
};

export type BillingResponse = {
    plan: string;
    status: string | null;
    retentionDays: number;
    usage: {
        tests: number;
        seats: number;
    };
    limits: {
        tests: number;
        seats: number | null;
    };
    estimateCents: number | null;
    resetsAt: string;
    over: boolean;
    enforced: boolean;
};

export type BillingRedirectResponse = {
    url: string;
};

export type ProjectStats = {
    status: 'pass' | 'fail' | 'flaky';
    passRate: number;
    runCount: number;
    testsCount: number;
    flakyCount: number;
    avgDurationSec: number | null;
    lastRunAt: string;
    ciProvider: string | null;
} | null;

export type RunBar = {
    startedAt: string;
    total: number;
    passed: number;
    failed: number;
    flaky: number;
    skipped: number;
    durationSec: number | null;
    commitSha: string | null;
    branch: string | null;
};

export type ProjectSummary = {
    id: string;
    name: string;
    description: string | null;
    repositoryUrl: string | null;
    defaultBranch: string | null;
    icon: string | null;
    color: string | null;
    createdAt: string;
    stats: ProjectStats;
    chartRuns: Array<RunBar>;
};

export type CreateProjectBody = {
    name: string;
    description?: string;
    repositoryUrl?: string;
    defaultBranch?: string;
    icon?: 'layers' | 'flask' | 'git' | 'code' | 'docs' | 'flow' | 'pulse' | 'home';
    color?: 'emerald' | 'indigo' | 'amber' | 'sky' | 'pink' | 'teal';
};

export type ProjectListResponse = {
    projects: Array<ProjectSummary>;
};

export type UpdateProjectBody = {
    name: string;
    description?: string;
    repositoryUrl?: string;
    defaultBranch?: string;
    icon?: 'layers' | 'flask' | 'git' | 'code' | 'docs' | 'flow' | 'pulse' | 'home';
    color?: 'emerald' | 'indigo' | 'amber' | 'sky' | 'pink' | 'teal';
};

export type ProjectDeletedResponse = {
    ok: true;
};

export type TestCaseSummary = {
    testId: string;
    title: string;
    titlePath: Array<string>;
    file: string;
    status: 'passed' | 'failed' | 'flaky' | 'skipped';
    durationMs: number;
    retries: number;
    line: number | null;
    lastRunAt: string;
};

export type TestExplorerResponse = {
    tests: Array<TestCaseSummary>;
    specFileCount: number;
};

export type FlakyTestSummary = TestCaseSummary & {
    flakeCount: number;
};

export type FlakyTestsResponse = {
    tests: Array<FlakyTestSummary>;
    runWindow: number;
};

export type TestHistoryEntry = {
    runId: string;
    status: 'passed' | 'failed' | 'flaky' | 'skipped';
    commitSha: string | null;
    branch: string | null;
    durationMs: number;
    startedAt: string;
};

export type RunGitRef = {
    id: string;
    commitSha: string | null;
    branch: string | null;
    repository: string | null;
    ciProvider: string | null;
    ciRunUrl: string | null;
} | null;

export type TestSourceRef = RunGitRef & ({
    line: number | null;
} | null);

export type TestDetailResponse = {
    test: TestCaseSummary;
    history: Array<TestHistoryEntry>;
    latestRun: RunGitRef;
    source: TestSourceRef;
};

export type RunCreatedResponse = {
    id: string;
};

export type CreateRunBody = {
    projectId: string;
    environment?: string;
    startedAt: string;
    commitSha?: string;
    branch?: string;
    prNumber?: number;
    repository?: string;
    authorEmail?: string;
    authorName?: string;
    ciProvider?: string;
    ciRunId?: string;
    ciRunUrl?: string;
    ciRunAttempt?: string;
    shardIndex?: number;
    shardTotal?: number;
};

export type FinalizeRunBody = {
    status: 'passed' | 'failed' | 'timedout' | 'interrupted';
    finishedAt: string;
    stats: {
        total: number;
        passed: number;
        failed: number;
        skipped: number;
        flaky: number;
    };
    shardIndex?: number;
};

export type CompleteRunResponse = {
    ok: true;
    completed: boolean;
};

export type CompleteRunBody = {
    projectId: string;
    ciRunId: string;
    ciRunAttempt?: string;
};

export type CreateExecutionsBody = {
    executions: Array<{
        id: string;
        testId: string;
        title: string;
        titlePath: Array<string>;
        file: string;
        projectName?: string;
        status: 'passed' | 'failed' | 'timedOut' | 'skipped' | 'interrupted';
        durationMs: number;
        retry: number;
        errorMessage?: string;
        line?: number;
        startedAt: string;
    }>;
    shardIndex?: number;
};

export type ArtifactUploadedResponse = {
    id: string;
    kind: 'trace' | 'screenshot' | 'video';
    sizeBytes: number;
};

export type UploadSourceBody = {
    file: string;
    content: string;
};

export type RunFiltersResponse = {
    branches: Array<string>;
    users: Array<{
        email: string;
        name: string | null;
    }>;
    environments: Array<string>;
    hasUnset: boolean;
};

export type RunSummary = {
    id: string;
    projectId: string;
    projectName: string;
    status: string;
    hadFailure: boolean;
    environment: string | null;
    commitSha: string | null;
    branch: string | null;
    prNumber: number | null;
    repository: string | null;
    authorEmail: string | null;
    authorName: string | null;
    ciProvider: string | null;
    ciRunId: string | null;
    ciRunUrl: string | null;
    startedAt: string;
    finishedAt: string | null;
    stats: {
        total: number;
        passed: number;
        failed: number;
        skipped: number;
        flaky: number;
    } | null;
    shardTotal: number | null;
    createdAt: string;
};

export type RunListResponse = {
    runs: Array<RunSummary>;
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
};

export type RunAggregate = {
    total: number;
    passed: number;
    failed: number;
    flaky: number;
    skipped: number;
    durationSec: number | null;
};

export type RunFileSummary = {
    file: string;
    total: number;
    passed: number;
    failed: number;
    flaky: number;
    skipped: number;
};

export type RunDetailResponse = {
    run: RunSummary;
    summary: RunAggregate;
    files: Array<RunFileSummary>;
};

export type RunDeletedResponse = {
    ok: true;
};

export type ArtifactSummary = {
    id: string;
    kind: 'trace' | 'screenshot' | 'video';
    contentType: string;
    sizeBytes: number;
    name: string | null;
    url: string | null;
};

export type AttemptSummary = {
    id: string;
    retry: number;
    status: string;
    durationMs: number;
    errorMessage: string | null;
    shardIndex: number | null;
    startedAt: string;
    artifacts: Array<ArtifactSummary>;
};

export type TestCase = {
    testId: string;
    title: string;
    titlePath: Array<string>;
    status: 'passed' | 'failed' | 'flaky' | 'skipped';
    attempts: Array<AttemptSummary>;
};

export type RunFileTestsResponse = {
    file: string;
    tests: Array<TestCase>;
};

export type ArtifactUrlResponse = {
    url: string;
};

export type SourceResponse = {
    file: string;
    content: string;
};

export type SecretKeySummary = {
    id: string;
    name: string;
    scope: 'org' | 'project';
    prefix: string;
    last4: string;
    project: {
        id: string;
        name: string;
        icon: string | null;
        color: string | null;
    } | null;
    createdAt: string;
    lastUsedAt: string | null;
};

export type SecretKeyListResponse = {
    keys: Array<SecretKeySummary>;
};

export type SecretKeyCreatedResponse = {
    id: string;
    name: string;
    scope: 'org' | 'project';
    prefix: string;
    last4: string;
    project: {
        id: string;
        name: string;
        icon: string | null;
        color: string | null;
    } | null;
    createdAt: string;
    lastUsedAt: string | null;
    token: string;
};

export type CreateSecretKeyBody = {
    name: string;
    scope: 'org' | 'project';
    projectId?: string;
};

export type SecretKeyDeletedResponse = {
    ok: true;
};

export type SlackStatusResponse = {
    configured: boolean;
    connected: boolean;
    status: 'connected' | 'error';
    teamName: string | null;
    defaultChannel: {
        id: string;
        name: string;
    } | null;
    triggerMode: 'every' | 'fail' | 'failflaky' | 'regression';
    detailLevel: 'compact' | 'full';
    layout: 'classic' | 'blockkit';
    connectedAt: string | null;
    lastError: string | null;
};

export type SlackInstallUrlResponse = {
    url: string;
};

export type UpdateSlackBody = {
    defaultChannelId?: string;
    defaultChannelName?: string;
    triggerMode?: 'every' | 'fail' | 'failflaky' | 'regression';
    detailLevel?: 'compact' | 'full';
    layout?: 'classic' | 'blockkit';
};

export type SlackOkResponse = {
    ok: true;
};

export type SlackChannelsResponse = {
    channels: Array<{
        id: string;
        name: string;
        isPrivate: boolean;
    }>;
};

export type SlackTestBody = {
    channelId?: string;
};

export type ProjectSlackResponse = {
    slackConnected: boolean;
    orgDefaultChannel: {
        id: string;
        name: string;
    } | null;
    enabled: boolean;
    channel: {
        id: string;
        name: string;
    } | null;
    effectiveChannel: {
        id: string;
        name: string;
    } | null;
    branches: Array<string>;
};

export type UpdateProjectSlackBody = {
    enabled: boolean;
    channelId?: string | null;
    channelName?: string | null;
    branches?: Array<string>;
};

export type SignupData = {
    body?: SignupBody;
    path?: never;
    query?: never;
    url: '/v1/auth/signup';
};

export type SignupErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Email exists
     */
    409: ApiError;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * Created
     */
    201: SignupResponse;
};

export type SignupResponse2 = SignupResponses[keyof SignupResponses];

export type LoginData = {
    body?: LoginBody;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid credentials or unverified email
     */
    401: ApiError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/logout';
};

export type LogoutErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type VerifyEmailData = {
    body?: VerifyEmailBody;
    path?: never;
    query?: never;
    url: '/v1/auth/verify-email';
};

export type VerifyEmailErrors = {
    /**
     * Invalid, expired, or used token
     */
    400: ApiError;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * Verified
     */
    200: VerifiedResponse;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type ResendVerificationData = {
    body?: ResendVerificationBody;
    path?: never;
    query?: never;
    url: '/v1/auth/resend-verification';
};

export type ResendVerificationResponses = {
    /**
     * Accepted
     */
    204: void;
};

export type ResendVerificationResponse = ResendVerificationResponses[keyof ResendVerificationResponses];

export type ForgotPasswordData = {
    body?: ForgotPasswordBody;
    path?: never;
    query?: never;
    url: '/v1/auth/forgot-password';
};

export type ForgotPasswordResponses = {
    /**
     * Accepted
     */
    204: void;
};

export type ForgotPasswordResponse = ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type ResetPasswordData = {
    body?: ResetPasswordBody;
    path?: never;
    query?: never;
    url: '/v1/auth/reset-password';
};

export type ResetPasswordErrors = {
    /**
     * Invalid, expired, or used token
     */
    400: ApiError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Password reset
     */
    200: ResetResponse;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type ListMyOAuthAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/me/oauth';
};

export type ListMyOAuthAccountsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type ListMyOAuthAccountsError = ListMyOAuthAccountsErrors[keyof ListMyOAuthAccountsErrors];

export type ListMyOAuthAccountsResponses = {
    /**
     * OK
     */
    200: OAuthAccountsResponse;
};

export type ListMyOAuthAccountsResponse = ListMyOAuthAccountsResponses[keyof ListMyOAuthAccountsResponses];

export type UnlinkMyOAuthAccountData = {
    body?: never;
    path: {
        provider: 'google' | 'github';
    };
    query?: never;
    url: '/v1/auth/me/oauth/{provider}';
};

export type UnlinkMyOAuthAccountErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Last login method
     */
    409: ApiError;
};

export type UnlinkMyOAuthAccountError = UnlinkMyOAuthAccountErrors[keyof UnlinkMyOAuthAccountErrors];

export type UnlinkMyOAuthAccountResponses = {
    /**
     * OK
     */
    200: AuthOkResponse;
};

export type UnlinkMyOAuthAccountResponse = UnlinkMyOAuthAccountResponses[keyof UnlinkMyOAuthAccountResponses];

export type UpdateMyPasswordData = {
    body?: UpdatePasswordBody;
    path?: never;
    query?: never;
    url: '/v1/auth/me/password';
};

export type UpdateMyPasswordErrors = {
    /**
     * Wrong current password
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type UpdateMyPasswordError = UpdateMyPasswordErrors[keyof UpdateMyPasswordErrors];

export type UpdateMyPasswordResponses = {
    /**
     * OK
     */
    200: AuthOkResponse;
};

export type UpdateMyPasswordResponse = UpdateMyPasswordResponses[keyof UpdateMyPasswordResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/me';
};

export type GetMeErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateMeData = {
    body?: UpdateMeBody;
    path?: never;
    query?: never;
    url: '/v1/auth/me';
};

export type UpdateMeErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type DeleteMyAvatarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/me/avatar';
};

export type DeleteMyAvatarErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type DeleteMyAvatarError = DeleteMyAvatarErrors[keyof DeleteMyAvatarErrors];

export type DeleteMyAvatarResponses = {
    /**
     * Removed
     */
    200: UserResponse;
};

export type DeleteMyAvatarResponse = DeleteMyAvatarResponses[keyof DeleteMyAvatarResponses];

export type UploadMyAvatarData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/me/avatar';
};

export type UploadMyAvatarErrors = {
    /**
     * No file
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Image too large
     */
    413: ApiError;
    /**
     * Unsupported image type
     */
    415: ApiError;
    /**
     * Storage failure
     */
    502: ApiError;
};

export type UploadMyAvatarError = UploadMyAvatarErrors[keyof UploadMyAvatarErrors];

export type UploadMyAvatarResponses = {
    /**
     * Stored
     */
    200: UserResponse;
};

export type UploadMyAvatarResponse = UploadMyAvatarResponses[keyof UploadMyAvatarResponses];

export type ListOrgsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/orgs';
};

export type ListOrgsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
};

export type ListOrgsError = ListOrgsErrors[keyof ListOrgsErrors];

export type ListOrgsResponses = {
    /**
     * OK
     */
    200: OrgListResponse;
};

export type ListOrgsResponse = ListOrgsResponses[keyof ListOrgsResponses];

export type CreateOrgData = {
    body?: CreateOrgBody;
    path?: never;
    query?: never;
    url: '/v1/orgs';
};

export type CreateOrgErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Per-account organization limit reached
     */
    403: ApiError;
};

export type CreateOrgError = CreateOrgErrors[keyof CreateOrgErrors];

export type CreateOrgResponses = {
    /**
     * Created
     */
    201: OrgResponse;
};

export type CreateOrgResponse = CreateOrgResponses[keyof CreateOrgResponses];

export type DeleteOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}';
};

export type DeleteOrgErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Organization not found
     */
    404: ApiError;
    /**
     * Organization still has projects
     */
    409: ApiError;
    /**
     * Stored files could not be removed
     */
    502: ApiError;
};

export type DeleteOrgError = DeleteOrgErrors[keyof DeleteOrgErrors];

export type DeleteOrgResponses = {
    /**
     * Deleted
     */
    200: OkResponse;
};

export type DeleteOrgResponse = DeleteOrgResponses[keyof DeleteOrgResponses];

export type GetOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}';
};

export type GetOrgErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type GetOrgError = GetOrgErrors[keyof GetOrgErrors];

export type GetOrgResponses = {
    /**
     * OK
     */
    200: OrgResponse;
};

export type GetOrgResponse = GetOrgResponses[keyof GetOrgResponses];

export type UpdateOrgData = {
    body?: UpdateOrgBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}';
};

export type UpdateOrgErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type UpdateOrgError = UpdateOrgErrors[keyof UpdateOrgErrors];

export type UpdateOrgResponses = {
    /**
     * OK
     */
    200: OrgResponse;
};

export type UpdateOrgResponse = UpdateOrgResponses[keyof UpdateOrgResponses];

export type DeleteOrgLogoData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/logo';
};

export type DeleteOrgLogoErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type DeleteOrgLogoError = DeleteOrgLogoErrors[keyof DeleteOrgLogoErrors];

export type DeleteOrgLogoResponses = {
    /**
     * Removed
     */
    200: OrgResponse;
};

export type DeleteOrgLogoResponse = DeleteOrgLogoResponses[keyof DeleteOrgLogoResponses];

export type UploadOrgLogoData = {
    body?: {
        file?: Blob | File;
    };
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/logo';
};

export type UploadOrgLogoErrors = {
    /**
     * No file
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
    /**
     * Logo too large
     */
    413: ApiError;
    /**
     * Unsupported image type
     */
    415: ApiError;
    /**
     * Storage failure
     */
    502: ApiError;
};

export type UploadOrgLogoError = UploadOrgLogoErrors[keyof UploadOrgLogoErrors];

export type UploadOrgLogoResponses = {
    /**
     * Stored
     */
    200: OrgResponse;
};

export type UploadOrgLogoResponse = UploadOrgLogoResponses[keyof UploadOrgLogoResponses];

export type ListOrgMembersData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/members';
};

export type ListOrgMembersErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type ListOrgMembersError = ListOrgMembersErrors[keyof ListOrgMembersErrors];

export type ListOrgMembersResponses = {
    /**
     * OK
     */
    200: MemberListResponse;
};

export type ListOrgMembersResponse = ListOrgMembersResponses[keyof ListOrgMembersResponses];

export type RemoveOrgMemberData = {
    body?: never;
    path: {
        orgId: string;
        userId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/members/{userId}';
};

export type RemoveOrgMemberErrors = {
    /**
     * Cannot remove self / last admin
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type RemoveOrgMemberError = RemoveOrgMemberErrors[keyof RemoveOrgMemberErrors];

export type RemoveOrgMemberResponses = {
    /**
     * Removed
     */
    200: OkResponse;
};

export type RemoveOrgMemberResponse = RemoveOrgMemberResponses[keyof RemoveOrgMemberResponses];

export type UpdateOrgMemberRoleData = {
    body?: UpdateMemberRoleBody;
    path: {
        orgId: string;
        userId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/members/{userId}';
};

export type UpdateOrgMemberRoleErrors = {
    /**
     * Cannot demote the last admin
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type UpdateOrgMemberRoleError = UpdateOrgMemberRoleErrors[keyof UpdateOrgMemberRoleErrors];

export type UpdateOrgMemberRoleResponses = {
    /**
     * Updated
     */
    200: OkResponse;
};

export type UpdateOrgMemberRoleResponse = UpdateOrgMemberRoleResponses[keyof UpdateOrgMemberRoleResponses];

export type ListOrgInvitationsData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/invitations';
};

export type ListOrgInvitationsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type ListOrgInvitationsError = ListOrgInvitationsErrors[keyof ListOrgInvitationsErrors];

export type ListOrgInvitationsResponses = {
    /**
     * OK
     */
    200: InvitationListResponse;
};

export type ListOrgInvitationsResponse = ListOrgInvitationsResponses[keyof ListOrgInvitationsResponses];

export type CreateOrgInvitationData = {
    body?: CreateInviteBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/invitations';
};

export type CreateOrgInvitationErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Free plan seat limit reached
     */
    402: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
    /**
     * Already a member
     */
    409: ApiError;
};

export type CreateOrgInvitationError = CreateOrgInvitationErrors[keyof CreateOrgInvitationErrors];

export type CreateOrgInvitationResponses = {
    /**
     * Invitation sent
     */
    201: InvitationSummary;
};

export type CreateOrgInvitationResponse = CreateOrgInvitationResponses[keyof CreateOrgInvitationResponses];

export type RevokeOrgInvitationData = {
    body?: never;
    path: {
        orgId: string;
        invitationId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/invitations/{invitationId}';
};

export type RevokeOrgInvitationErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type RevokeOrgInvitationError = RevokeOrgInvitationErrors[keyof RevokeOrgInvitationErrors];

export type RevokeOrgInvitationResponses = {
    /**
     * Revoked
     */
    200: OkResponse;
};

export type RevokeOrgInvitationResponse = RevokeOrgInvitationResponses[keyof RevokeOrgInvitationResponses];

export type PreviewInvitationData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/v1/invitations/{token}';
};

export type PreviewInvitationErrors = {
    /**
     * Not found
     */
    404: ApiError;
};

export type PreviewInvitationError = PreviewInvitationErrors[keyof PreviewInvitationErrors];

export type PreviewInvitationResponses = {
    /**
     * OK
     */
    200: InvitePreviewResponse;
};

export type PreviewInvitationResponse = PreviewInvitationResponses[keyof PreviewInvitationResponses];

export type AcceptInvitationData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/v1/invitations/{token}/accept';
};

export type AcceptInvitationErrors = {
    /**
     * Expired
     */
    400: ApiError;
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Free plan seat limit reached
     */
    402: ApiError;
    /**
     * Email mismatch
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type AcceptInvitationError = AcceptInvitationErrors[keyof AcceptInvitationErrors];

export type AcceptInvitationResponses = {
    /**
     * Joined
     */
    200: AcceptInviteResponse;
};

export type AcceptInvitationResponse = AcceptInvitationResponses[keyof AcceptInvitationResponses];

export type GetOrgBillingData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/billing';
};

export type GetOrgBillingErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Organization not found
     */
    404: ApiError;
};

export type GetOrgBillingError = GetOrgBillingErrors[keyof GetOrgBillingErrors];

export type GetOrgBillingResponses = {
    /**
     * OK
     */
    200: BillingResponse;
};

export type GetOrgBillingResponse = GetOrgBillingResponses[keyof GetOrgBillingResponses];

export type CreateBillingCheckoutData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/billing/checkout';
};

export type CreateBillingCheckoutErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Organization not found
     */
    404: ApiError;
    /**
     * Billing not configured
     */
    503: ApiError;
};

export type CreateBillingCheckoutError = CreateBillingCheckoutErrors[keyof CreateBillingCheckoutErrors];

export type CreateBillingCheckoutResponses = {
    /**
     * Hosted checkout URL
     */
    200: BillingRedirectResponse;
};

export type CreateBillingCheckoutResponse = CreateBillingCheckoutResponses[keyof CreateBillingCheckoutResponses];

export type CreateBillingPortalData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/billing/portal';
};

export type CreateBillingPortalErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Organization not found
     */
    404: ApiError;
    /**
     * Billing not configured
     */
    503: ApiError;
};

export type CreateBillingPortalError = CreateBillingPortalErrors[keyof CreateBillingPortalErrors];

export type CreateBillingPortalResponses = {
    /**
     * Customer portal URL
     */
    200: BillingRedirectResponse;
};

export type CreateBillingPortalResponse = CreateBillingPortalResponses[keyof CreateBillingPortalResponses];

export type ListOrgProjectsData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/projects';
};

export type ListOrgProjectsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Org not found
     */
    404: ApiError;
};

export type ListOrgProjectsError = ListOrgProjectsErrors[keyof ListOrgProjectsErrors];

export type ListOrgProjectsResponses = {
    /**
     * OK
     */
    200: ProjectListResponse;
};

export type ListOrgProjectsResponse = ListOrgProjectsResponses[keyof ListOrgProjectsResponses];

export type CreateProjectData = {
    body?: CreateProjectBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/projects';
};

export type CreateProjectErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Org not found
     */
    404: ApiError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Created
     */
    201: ProjectSummary;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type DeleteProjectErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
    /**
     * Stored files could not be removed
     */
    502: ApiError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Deleted
     */
    200: ProjectDeletedResponse;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type GetProjectErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * OK
     */
    200: ProjectSummary;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body?: UpdateProjectBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type UpdateProjectErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * OK
     */
    200: ProjectSummary;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type ListProjectTestsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/v1/projects/{projectId}/tests';
};

export type ListProjectTestsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type ListProjectTestsError = ListProjectTestsErrors[keyof ListProjectTestsErrors];

export type ListProjectTestsResponses = {
    /**
     * OK
     */
    200: TestExplorerResponse;
};

export type ListProjectTestsResponse = ListProjectTestsResponses[keyof ListProjectTestsResponses];

export type ListProjectFlakyTestsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/v1/projects/{projectId}/flaky-tests';
};

export type ListProjectFlakyTestsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type ListProjectFlakyTestsError = ListProjectFlakyTestsErrors[keyof ListProjectFlakyTestsErrors];

export type ListProjectFlakyTestsResponses = {
    /**
     * OK
     */
    200: FlakyTestsResponse;
};

export type ListProjectFlakyTestsResponse = ListProjectFlakyTestsResponses[keyof ListProjectFlakyTestsResponses];

export type GetProjectTestData = {
    body?: never;
    path: {
        projectId: string;
        testId: string;
    };
    query?: never;
    url: '/v1/projects/{projectId}/tests/{testId}';
};

export type GetProjectTestErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type GetProjectTestError = GetProjectTestErrors[keyof GetProjectTestErrors];

export type GetProjectTestResponses = {
    /**
     * OK
     */
    200: TestDetailResponse;
};

export type GetProjectTestResponse = GetProjectTestResponses[keyof GetProjectTestResponses];

export type CreateRunData = {
    body?: CreateRunBody;
    path?: never;
    query?: never;
    url: '/v1/runs';
};

export type CreateRunErrors = {
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type CreateRunError = CreateRunErrors[keyof CreateRunErrors];

export type CreateRunResponses = {
    /**
     * Created
     */
    201: RunCreatedResponse;
};

export type CreateRunResponse = CreateRunResponses[keyof CreateRunResponses];

export type DeleteRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}';
};

export type DeleteRunErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
    /**
     * Stored files could not be removed
     */
    502: ApiError;
};

export type DeleteRunError = DeleteRunErrors[keyof DeleteRunErrors];

export type DeleteRunResponses = {
    /**
     * Deleted
     */
    200: RunDeletedResponse;
};

export type DeleteRunResponse = DeleteRunResponses[keyof DeleteRunResponses];

export type GetRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}';
};

export type GetRunErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
};

export type GetRunError = GetRunErrors[keyof GetRunErrors];

export type GetRunResponses = {
    /**
     * OK
     */
    200: RunDetailResponse;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type FinalizeRunData = {
    body?: FinalizeRunBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}';
};

export type FinalizeRunErrors = {
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
};

export type FinalizeRunError = FinalizeRunErrors[keyof FinalizeRunErrors];

export type FinalizeRunResponses = {
    /**
     * OK
     */
    200: OkResponse & {
        ok?: true;
    };
};

export type FinalizeRunResponse = FinalizeRunResponses[keyof FinalizeRunResponses];

export type CompleteRunData = {
    body?: CompleteRunBody;
    path?: never;
    query?: never;
    url: '/v1/runs/complete';
};

export type CompleteRunErrors = {
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Project not found / out of scope
     */
    404: ApiError;
};

export type CompleteRunError = CompleteRunErrors[keyof CompleteRunErrors];

export type CompleteRunResponses = {
    /**
     * OK
     */
    200: CompleteRunResponse;
};

export type CompleteRunResponse2 = CompleteRunResponses[keyof CompleteRunResponses];

export type CreateExecutionsData = {
    body?: CreateExecutionsBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}/executions';
};

export type CreateExecutionsErrors = {
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Free plan test limit reached
     */
    402: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
};

export type CreateExecutionsError = CreateExecutionsErrors[keyof CreateExecutionsErrors];

export type CreateExecutionsResponses = {
    /**
     * OK
     */
    200: OkResponse & {
        ok?: true;
    };
};

export type CreateExecutionsResponse = CreateExecutionsResponses[keyof CreateExecutionsResponses];

export type UploadArtifactData = {
    body?: never;
    path: {
        id: string;
        eid: string;
        kind: 'trace' | 'screenshot' | 'video';
    };
    query?: never;
    url: '/v1/runs/{id}/executions/{eid}/artifacts/{kind}';
};

export type UploadArtifactErrors = {
    /**
     * Empty body
     */
    400: ApiError;
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Run/execution not found
     */
    404: ApiError;
    /**
     * Artifact too large
     */
    413: ApiError;
    /**
     * Storage failure
     */
    502: ApiError;
};

export type UploadArtifactError = UploadArtifactErrors[keyof UploadArtifactErrors];

export type UploadArtifactResponses = {
    /**
     * Stored
     */
    200: ArtifactUploadedResponse;
};

export type UploadArtifactResponse = UploadArtifactResponses[keyof UploadArtifactResponses];

export type UploadRunSourceData = {
    body?: UploadSourceBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}/source';
};

export type UploadRunSourceErrors = {
    /**
     * Invalid or missing API key
     */
    401: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
};

export type UploadRunSourceError = UploadRunSourceErrors[keyof UploadRunSourceErrors];

export type UploadRunSourceResponses = {
    /**
     * Stored
     */
    200: OkResponse & {
        ok?: true;
    };
};

export type UploadRunSourceResponse = UploadRunSourceResponses[keyof UploadRunSourceResponses];

export type GetProjectRunFiltersData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/v1/projects/{projectId}/runs/filters';
};

export type GetProjectRunFiltersErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type GetProjectRunFiltersError = GetProjectRunFiltersErrors[keyof GetProjectRunFiltersErrors];

export type GetProjectRunFiltersResponses = {
    /**
     * OK
     */
    200: RunFiltersResponse;
};

export type GetProjectRunFiltersResponse = GetProjectRunFiltersResponses[keyof GetProjectRunFiltersResponses];

export type ListProjectRunsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        status?: 'all' | 'passed' | 'failed' | 'flaky';
        branch?: string;
        user?: string;
        environment?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/v1/projects/{projectId}/runs';
};

export type ListProjectRunsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Project not found
     */
    404: ApiError;
};

export type ListProjectRunsError = ListProjectRunsErrors[keyof ListProjectRunsErrors];

export type ListProjectRunsResponses = {
    /**
     * OK
     */
    200: RunListResponse;
};

export type ListProjectRunsResponse = ListProjectRunsResponses[keyof ListProjectRunsResponses];

export type GetRunFileTestsData = {
    body?: never;
    path: {
        runId: string;
    };
    query: {
        file: string;
    };
    url: '/v1/runs/{runId}/tests';
};

export type GetRunFileTestsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Run not found
     */
    404: ApiError;
};

export type GetRunFileTestsError = GetRunFileTestsErrors[keyof GetRunFileTestsErrors];

export type GetRunFileTestsResponses = {
    /**
     * OK
     */
    200: RunFileTestsResponse;
};

export type GetRunFileTestsResponse = GetRunFileTestsResponses[keyof GetRunFileTestsResponses];

export type GetArtifactUrlData = {
    body?: never;
    path: {
        attachmentId: string;
    };
    query?: never;
    url: '/v1/attachments/{attachmentId}/url';
};

export type GetArtifactUrlErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type GetArtifactUrlError = GetArtifactUrlErrors[keyof GetArtifactUrlErrors];

export type GetArtifactUrlResponses = {
    /**
     * OK
     */
    200: ArtifactUrlResponse;
};

export type GetArtifactUrlResponse = GetArtifactUrlResponses[keyof GetArtifactUrlResponses];

export type GetRunSourceData = {
    body?: never;
    path: {
        runId: string;
    };
    query: {
        file: string;
    };
    url: '/v1/runs/{runId}/source';
};

export type GetRunSourceErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Source not found
     */
    404: ApiError;
};

export type GetRunSourceError = GetRunSourceErrors[keyof GetRunSourceErrors];

export type GetRunSourceResponses = {
    /**
     * OK
     */
    200: SourceResponse;
};

export type GetRunSourceResponse = GetRunSourceResponses[keyof GetRunSourceResponses];

export type ListSecretKeysData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/secret-keys';
};

export type ListSecretKeysErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Org not found
     */
    404: ApiError;
};

export type ListSecretKeysError = ListSecretKeysErrors[keyof ListSecretKeysErrors];

export type ListSecretKeysResponses = {
    /**
     * OK
     */
    200: SecretKeyListResponse;
};

export type ListSecretKeysResponse = ListSecretKeysResponses[keyof ListSecretKeysResponses];

export type CreateSecretKeyData = {
    body?: CreateSecretKeyBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/secret-keys';
};

export type CreateSecretKeyErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Org or project not found
     */
    404: ApiError;
};

export type CreateSecretKeyError = CreateSecretKeyErrors[keyof CreateSecretKeyErrors];

export type CreateSecretKeyResponses = {
    /**
     * Created
     */
    201: SecretKeyCreatedResponse;
};

export type CreateSecretKeyResponse = CreateSecretKeyResponses[keyof CreateSecretKeyResponses];

export type DeleteSecretKeyData = {
    body?: never;
    path: {
        orgId: string;
        keyId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/secret-keys/{keyId}';
};

export type DeleteSecretKeyErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type DeleteSecretKeyError = DeleteSecretKeyErrors[keyof DeleteSecretKeyErrors];

export type DeleteSecretKeyResponses = {
    /**
     * Revoked
     */
    200: SecretKeyDeletedResponse;
};

export type DeleteSecretKeyResponse = DeleteSecretKeyResponses[keyof DeleteSecretKeyResponses];

export type DisconnectOrgSlackData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/integrations/slack';
};

export type DisconnectOrgSlackErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type DisconnectOrgSlackError = DisconnectOrgSlackErrors[keyof DisconnectOrgSlackErrors];

export type DisconnectOrgSlackResponses = {
    /**
     * OK
     */
    200: SlackOkResponse;
};

export type DisconnectOrgSlackResponse = DisconnectOrgSlackResponses[keyof DisconnectOrgSlackResponses];

export type GetOrgSlackIntegrationData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/integrations/slack';
};

export type GetOrgSlackIntegrationErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type GetOrgSlackIntegrationError = GetOrgSlackIntegrationErrors[keyof GetOrgSlackIntegrationErrors];

export type GetOrgSlackIntegrationResponses = {
    /**
     * OK
     */
    200: SlackStatusResponse;
};

export type GetOrgSlackIntegrationResponse = GetOrgSlackIntegrationResponses[keyof GetOrgSlackIntegrationResponses];

export type UpdateOrgSlackIntegrationData = {
    body?: UpdateSlackBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/integrations/slack';
};

export type UpdateOrgSlackIntegrationErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found / not connected
     */
    404: ApiError;
};

export type UpdateOrgSlackIntegrationError = UpdateOrgSlackIntegrationErrors[keyof UpdateOrgSlackIntegrationErrors];

export type UpdateOrgSlackIntegrationResponses = {
    /**
     * OK
     */
    200: SlackStatusResponse;
};

export type UpdateOrgSlackIntegrationResponse = UpdateOrgSlackIntegrationResponses[keyof UpdateOrgSlackIntegrationResponses];

export type InstallOrgSlackData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/integrations/slack/install';
};

export type InstallOrgSlackErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
    /**
     * Slack not configured
     */
    503: ApiError;
};

export type InstallOrgSlackError = InstallOrgSlackErrors[keyof InstallOrgSlackErrors];

export type InstallOrgSlackResponses = {
    /**
     * OK
     */
    200: SlackInstallUrlResponse;
};

export type InstallOrgSlackResponse = InstallOrgSlackResponses[keyof InstallOrgSlackResponses];

export type ListOrgSlackChannelsData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/integrations/slack/channels';
};

export type ListOrgSlackChannelsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
    /**
     * Slack not connected
     */
    409: ApiError;
};

export type ListOrgSlackChannelsError = ListOrgSlackChannelsErrors[keyof ListOrgSlackChannelsErrors];

export type ListOrgSlackChannelsResponses = {
    /**
     * OK
     */
    200: SlackChannelsResponse;
};

export type ListOrgSlackChannelsResponse = ListOrgSlackChannelsResponses[keyof ListOrgSlackChannelsResponses];

export type TestOrgSlackData = {
    body?: SlackTestBody;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/v1/orgs/{orgId}/integrations/slack/test';
};

export type TestOrgSlackErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
    /**
     * Not connected / no channel
     */
    409: ApiError;
    /**
     * Slack rejected the message
     */
    502: ApiError;
};

export type TestOrgSlackError = TestOrgSlackErrors[keyof TestOrgSlackErrors];

export type TestOrgSlackResponses = {
    /**
     * Sent
     */
    200: SlackOkResponse;
};

export type TestOrgSlackResponse = TestOrgSlackResponses[keyof TestOrgSlackResponses];

export type GetProjectSlackSettingsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/v1/projects/{projectId}/integrations/slack';
};

export type GetProjectSlackSettingsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type GetProjectSlackSettingsError = GetProjectSlackSettingsErrors[keyof GetProjectSlackSettingsErrors];

export type GetProjectSlackSettingsResponses = {
    /**
     * OK
     */
    200: ProjectSlackResponse;
};

export type GetProjectSlackSettingsResponse = GetProjectSlackSettingsResponses[keyof GetProjectSlackSettingsResponses];

export type UpdateProjectSlackSettingsData = {
    body?: UpdateProjectSlackBody;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/v1/projects/{projectId}/integrations/slack';
};

export type UpdateProjectSlackSettingsErrors = {
    /**
     * Not authenticated
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Not found
     */
    404: ApiError;
};

export type UpdateProjectSlackSettingsError = UpdateProjectSlackSettingsErrors[keyof UpdateProjectSlackSettingsErrors];

export type UpdateProjectSlackSettingsResponses = {
    /**
     * OK
     */
    200: ProjectSlackResponse;
};

export type UpdateProjectSlackSettingsResponse = UpdateProjectSlackSettingsResponses[keyof UpdateProjectSlackSettingsResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};